import { useState } from 'react'
import { DashboardLayout } from '../components/DashboardLayout.jsx'
import { FeedbackModal } from '../components/FeedbackModal.jsx'
import { expertApplications, initialQuestions, moderationQueue, userAccounts } from '../data/platformData.js'

const tabs = [{ id: 'overview', label: 'Overview' }, { id: 'applications', label: 'Expert approvals' }, { id: 'escalations', label: 'Escalations' }, { id: 'moderation', label: 'Moderation' }, { id: 'categories', label: 'Categories' }, { id: 'users', label: 'User accounts' }, { id: 'admins', label: 'Admin team' }]
const activity = [{ title: 'Question Q-2060 auto-escalated', detail: 'No expert response within the configured SLA.', time: '2 min' }, { title: 'Maya R. approved as expert', detail: 'Checkout specialist added to the verified pool.', time: '18 min' }, { title: 'Content report resolved', detail: 'Duplicate promotional answer was removed.', time: '42 min' }, { title: 'Operator account restored', detail: 'Access was restored after manual review.', time: '1 hr' }]

export function AdminDashboard({ user, onLogout }) {
  const [tab, setTab] = useState('overview')
  const [apps, setApps] = useState(expertApplications)
  const [items, setItems] = useState(moderationQueue)
  const [accounts, setAccounts] = useState(userAccounts)
  const [hours, setHours] = useState(24)
  const [feedback, setFeedback] = useState(null)
  const [userSearch, setUserSearch] = useState('')
  const [categories, setCategories] = useState([{ id: 1, name: 'Checkout', description: 'Cart, checkout flow, shipping, and order completion.', status: 'Active', questions: 38 }, { id: 2, name: 'Payments', description: 'Payment gateways, failed charges, refunds, and payouts.', status: 'Active', questions: 27 }, { id: 3, name: 'Theme / Design', description: 'Storefront layouts, responsive design, and visual issues.', status: 'Active', questions: 22 }, { id: 4, name: 'Apps', description: 'Third-party applications, integrations, and conflicts.', status: 'Active', questions: 13 }, { id: 5, name: 'Other', description: 'Issues that do not match an existing support category.', status: 'Active', questions: 6 }])
  const [editingCategory, setEditingCategory] = useState(null)
  const [createCategoryOpen, setCreateCategoryOpen] = useState(false)
  const [roleFilter, setRoleFilter] = useState('All roles')
  const [statusFilter, setStatusFilter] = useState('All statuses')
  const [addAdminOpen, setAddAdminOpen] = useState(false)
  const [adminTeam, setAdminTeam] = useState([{ id: 1, name: user.name, email: user.email, access: 'Super Admin', status: 'Active', added: 'Platform owner' }, { id: 2, name: 'Jordan Admin', email: 'jordan@ecomsupport.example', access: 'Moderator', status: 'Active', added: '12 Jun 2026' }])
  const pendingApps = apps.filter((item) => item.status === 'Pending review').length
  const escalated = initialQuestions.filter((item) => item.escalated || item.responses === 0)

  const review = (name, status) => { setApps((current) => current.map((item) => item.name === name ? { ...item, status } : item)); setFeedback({ title: `Application ${status.toLowerCase()}`, message: `${name} has been ${status.toLowerCase()} and will be notified of this decision.` }) }
  const toggleAccount = (name) => { const account = accounts.find((item) => item.name === name); const nextStatus = account.status === 'Suspended' ? 'Active' : 'Suspended'; setAccounts((current) => current.map((item) => item.name === name ? { ...item, status: nextStatus } : item)); setFeedback({ title: `Account ${nextStatus === 'Active' ? 'restored' : 'suspended'}`, message: `${name}'s account is now ${nextStatus.toLowerCase()}.` }) }
  const resolveItem = (item) => { setItems((current) => current.filter((entry) => entry.id !== item.id)); setFeedback({ title: item.id.startsWith('MOD') ? 'Content removed' : 'Queue item resolved', message: 'The moderation queue and audit activity have been updated.' }) }
  const createCategory = (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const name = data.get('name').trim(); if (categories.some((item) => item.name.toLowerCase() === name.toLowerCase())) { setFeedback({ title: 'Category already exists', message: 'Choose a different category name or update the existing category.' }); return } setCategories((current) => [...current, { id: Date.now(), name, description: data.get('description').trim(), status: 'Active', questions: 0 }]); setCreateCategoryOpen(false); setFeedback({ title: 'Category created', message: `${name} is now available for new support questions.` }) }
  const toggleCategory = (id) => setCategories((current) => current.map((item) => item.id === id ? { ...item, status: item.status === 'Active' ? 'Inactive' : 'Active' } : item))
  const removeCategory = (category) => { if (category.questions > 0) { setFeedback({ title: 'Category cannot be removed', message: `${category.name} has existing questions. Set it to inactive instead to preserve archived content.` }); return } setCategories((current) => current.filter((item) => item.id !== category.id)); setFeedback({ title: 'Category removed', message: `${category.name} was removed from the support form.` }) }
  const saveCategoryEdit = (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const name = data.get('name').trim(); if (categories.some((item) => item.id !== editingCategory.id && item.name.toLowerCase() === name.toLowerCase())) { setFeedback({ title: 'Category name already exists', message: 'Choose a unique name before saving this category.' }); return } setCategories((current) => current.map((item) => item.id === editingCategory.id ? { ...item, name, description: data.get('description').trim() } : item)); setEditingCategory(null); setFeedback({ title: 'Category updated', message: `${name} and its description were updated successfully.` }) }
  const addAdmin = (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const email = data.get('email').trim(); if (adminTeam.some((item) => item.email.toLowerCase() === email.toLowerCase())) { setFeedback({ title: 'Admin already exists', message: 'This email address already belongs to an admin team member.' }); return } const name = data.get('name').trim(); setAdminTeam((current) => [...current, { id: Date.now(), name, email, access: data.get('access'), status: 'Invitation sent', added: 'Just now' }]); setAddAdminOpen(false); setFeedback({ title: 'Admin invitation created', message: `${name} will receive instructions to activate their ${data.get('access')} account.` }) }

  return <DashboardLayout user={user} onLogout={onLogout} title={tab === 'overview' ? 'Operations overview' : tabs.find((item) => item.id === tab).label} subtitle="Keep support responsive, safe, and accountable." tabs={tabs} activeTab={tab} onTabChange={setTab}>
    {tab === 'overview' && <>
      <section className="admin-command-banner"><div><p className="eyebrow">Platform command center</p><h2>Everything that needs attention, in one place.</h2><p>Monitor support coverage, expert quality, safety, and user access across the community.</p></div><div className="admin-health"><span className="health-ring"><strong>96%</strong><small>SLA</small></span><div><strong>Platform is healthy</strong><p>Most questions are answered within {hours} hours.</p></div></div></section>
      <div className="admin-metric-grid"><button onClick={() => setTab('escalations')}><span className="admin-metric-icon urgent">!</span><div><small>Needs immediate attention</small><strong>{escalated.length}</strong><span>Escalated questions</span></div><i>View queue →</i></button><button onClick={() => setTab('applications')}><span className="admin-metric-icon">✓</span><div><small>Awaiting review</small><strong>{pendingApps}</strong><span>Expert applications</span></div><i>Review now →</i></button><button onClick={() => setTab('moderation')}><span className="admin-metric-icon warning">◇</span><div><small>Content safety</small><strong>{items.length}</strong><span>Moderation items</span></div><i>Open queue →</i></button><button onClick={() => setTab('users')}><span className="admin-metric-icon blue">●</span><div><small>Community accounts</small><strong>{accounts.length}</strong><span>Users in prototype</span></div><i>Manage users →</i></button></div>
      <div className="admin-overview-grid"><section className="panel admin-priority-panel"><div className="board-toolbar"><div><p className="eyebrow">Priority queue</p><h4>Requires admin attention</h4><p>Ordered by urgency and time waiting.</p></div><button className="text-button" onClick={() => setTab('escalations')}>View all →</button></div>{escalated.map((question) => <article className="admin-priority-row" key={question.id}><span className="priority-dot" aria-hidden="true"/><div><strong>{question.title}</strong><p>{question.id} · {question.category} · Waiting {question.age}</p></div><span className="status-badge critical">{question.status}</span><button className="secondary-button compact" onClick={() => setFeedback({ title: 'Experts notified', message: `Additional available experts were notified about ${question.id}.` })}>Notify experts</button></article>)}</section><section className="panel admin-activity"><div className="form-header"><p className="eyebrow">Audit activity</p><h4>Recent platform actions</h4></div><div className="activity-timeline">{activity.map((item) => <article key={item.title}><span aria-hidden="true"/><div><strong>{item.title}</strong><p>{item.detail}</p></div><time>{item.time}</time></article>)}</div></section></div>
      <div className="admin-insight-grid"><section className="panel"><p className="eyebrow">Support demand</p><h4>Questions by category</h4><div className="category-bars">{[['Checkout',38],['Payments',27],['Theme / Design',22],['Apps',13]].map(([label,value]) => <div key={label}><span><strong>{label}</strong><small>{value}%</small></span><i><b style={{ width: `${value}%` }}/></i></div>)}</div></section><section className="panel"><p className="eyebrow">Expert coverage</p><h4>Verified pool health</h4><div className="coverage-summary"><strong>142</strong><span>active verified experts</span></div><div className="coverage-chips"><span>Checkout <b>42</b></span><span>Payments <b>35</b></span><span>Themes <b>39</b></span><span>Apps <b>26</b></span></div></section><section className="panel"><p className="eyebrow">Community quality</p><h4>Last 30 days</h4><div className="quality-list"><div><span>Helpful answer rating</span><strong>4.8/5</strong></div><div><span>Accepted solution rate</span><strong>89%</strong></div><div><span>Reports resolved</span><strong>97%</strong></div></div></section></div>
    </>}
    {tab === 'applications' && <section className="panel admin-table-panel"><div className="board-toolbar"><div><p className="eyebrow">Trust and verification</p><h4>Expert application queue</h4><p>Review experience before granting answer privileges.</p></div><span className="pill">{pendingApps} pending</span></div><div className="table-wrap"><table><thead><tr><th>Applicant</th><th>Specialty</th><th>Score</th><th>Status</th><th>Decision</th></tr></thead><tbody>{apps.map((item) => <tr key={item.name}><td><strong>{item.name}</strong></td><td>{item.specialty}</td><td>{item.score}/100</td><td><span className="status-badge normal">{item.status}</span></td><td><div className="approval-buttons"><button className="text-button" onClick={() => review(item.name, 'Approved')}>Approve</button><button className="text-button danger" onClick={() => review(item.name, 'Rejected')}>Reject</button></div></td></tr>)}</tbody></table></div></section>}
    {tab === 'escalations' && <div className="admin-settings-layout"><section className="panel"><div className="form-header"><p className="eyebrow">Response assurance</p><h4>Escalation queue</h4><p>Questions that need additional expert attention.</p></div>{escalated.map((question) => <div className="queue-item" key={question.id}><div><strong>{question.title}</strong><p>{question.category} · {question.age}</p></div><button className="secondary-button compact" onClick={() => setFeedback({ title: 'Experts notified', message: `Additional experts were notified about ${question.id}.` })}>Notify experts</button></div>)}</section><aside className="panel escalation-setting"><span className="feature-icon" aria-hidden="true">⏱</span><h4>Automatic escalation</h4><p>Notify additional experts and admins after a question has no response.</p><label>Threshold: {hours} hours<input type="range" min="6" max="48" step="6" value={hours} onChange={(event) => setHours(Number(event.target.value))}/></label><div className="threshold-scale"><span>6h</span><span>48h</span></div></aside></div>}
    {tab === 'moderation' && <section className="panel"><div className="board-toolbar"><div><p className="eyebrow">Content safety</p><h4>Moderation queue</h4><p>Review flagged, low-quality, or inappropriate activity.</p></div><span className="pill critical-pill">{items.length} open</span></div>{items.length ? items.map((item) => <article className="moderation-card" key={item.id}><span className="admin-metric-icon warning">◇</span><div><strong>{item.applicant}</strong><p>{item.specialty}</p><small>{item.id} · {item.submitted}</small></div><span className="pill">{item.decision}</span><button className="text-button danger" onClick={() => resolveItem(item)}>{item.id.startsWith('MOD') ? 'Remove content' : 'Resolve item'}</button></article>) : <div className="empty-state"><strong>Queue is clear</strong><p>There are no outstanding moderation items.</p></div>}</section>}
    {tab === 'categories' && <section className="panel category-list-panel full-width-categories"><div className="board-toolbar"><div><p className="eyebrow">Question organization</p><h4>Support categories</h4><p>Control how operators classify questions and browse solutions.</p></div><div className="header-actions"><span className="pill">{categories.filter((item) => item.status === 'Active').length} active</span><button className="primary-button" onClick={() => setCreateCategoryOpen(true)}>＋ Create category</button></div></div><div className="category-admin-list">{categories.map((category) => <article key={category.id}><span className="category-admin-icon" aria-hidden="true">{category.name.charAt(0)}</span><div><strong>{category.name}</strong><p>{category.description}</p><small>{category.questions} questions assigned</small></div><span className={`status-badge ${category.status === 'Active' ? 'normal' : ''}`}>{category.status}</span><div className="category-actions"><button className="text-button" onClick={() => setEditingCategory(category)}>Edit</button><button className="text-button" onClick={() => { toggleCategory(category.id); setFeedback({ title: `Category ${category.status === 'Active' ? 'deactivated' : 'activated'}`, message: `${category.name} has been updated successfully.` }) }}>{category.status === 'Active' ? 'Deactivate' : 'Activate'}</button><button className="text-button danger" onClick={() => removeCategory(category)}>Remove</button></div></article>)}</div></section>}
    {tab === 'users' && <section className="panel admin-table-panel"><div className="board-toolbar"><div><p className="eyebrow">Account controls</p><h4>All user accounts</h4><p>Search and filter by role or account status.</p></div><div className="user-filter-bar"><label><span className="sr-only">Search users</span><input type="search" placeholder="Search users" value={userSearch} onChange={(event) => setUserSearch(event.target.value)} /></label><label><span className="sr-only">Filter by role</span><select value={roleFilter} onChange={(event) => setRoleFilter(event.target.value)}><option>All roles</option><option>Operator</option><option>Verified Expert</option><option>Moderator</option><option>Expert applicant</option></select></label><label><span className="sr-only">Filter by status</span><select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value)}><option>All statuses</option><option>Active</option><option>Suspended</option><option>Pending review</option></select></label></div></div><div className="table-wrap"><table><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Last seen</th><th>Action</th></tr></thead><tbody>{accounts.filter((account) => `${account.name} ${account.role} ${account.status}`.toLowerCase().includes(userSearch.toLowerCase()) && (roleFilter === 'All roles' || account.role === roleFilter) && (statusFilter === 'All statuses' || account.status === statusFilter)).map((account) => <tr key={account.name}><td><strong>{account.name}</strong></td><td>{account.role}</td><td><span className={`status-badge ${account.status === 'Suspended' ? 'critical' : 'normal'}`}>{account.status}</span></td><td>{account.lastSeen}</td><td><button className="text-button" onClick={() => toggleAccount(account.name)}>{account.status === 'Suspended' ? 'Restore' : 'Suspend'}</button></td></tr>)}</tbody></table></div></section>}
    {tab === 'admins' && <section className="panel admin-team-panel"><div className="board-toolbar"><div><p className="eyebrow">Super Admin controls</p><h4>Moderator and admin team</h4><p>Admin accounts are invitation-only and cannot be created through public signup.</p></div><button className="primary-button" onClick={() => setAddAdminOpen(true)}>＋ Add admin</button></div><div className="admin-access-note"><span aria-hidden="true">◆</span><div><strong>You are acting as Super Admin</strong><p>Only Super Admins can invite, change access, or deactivate other administrators.</p></div></div><div className="table-wrap"><table><thead><tr><th>Team member</th><th>Access level</th><th>Status</th><th>Added</th><th>Action</th></tr></thead><tbody>{adminTeam.map((admin) => <tr key={admin.id}><td><strong>{admin.name}</strong><small className="table-subtext">{admin.email}</small></td><td><span className="pill">{admin.access}</span></td><td><span className="status-badge normal">{admin.status}</span></td><td>{admin.added}</td><td>{admin.access === 'Super Admin' ? <span className="edit-locked">Protected owner</span> : <button className="text-button danger" onClick={() => { setAdminTeam((items) => items.map((item) => item.id === admin.id ? { ...item, status: item.status === 'Deactivated' ? 'Active' : 'Deactivated' } : item)); setFeedback({ title: admin.status === 'Deactivated' ? 'Admin restored' : 'Admin deactivated', message: `${admin.name}'s administrative access was updated.` }) }}>{admin.status === 'Deactivated' ? 'Restore access' : 'Deactivate'}</button>}</td></tr>)}</tbody></table></div></section>}
    {editingCategory && <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setEditingCategory(null) }}><section className="confirmation-modal category-edit-modal" role="dialog" aria-modal="true" aria-labelledby="edit-category-title"><p className="eyebrow">Category settings</p><h2 id="edit-category-title">Edit category</h2><p>Changes will update how this category appears throughout the platform.</p><form onSubmit={saveCategoryEdit}><label>Category name<input name="name" defaultValue={editingCategory.name} required maxLength="40" /></label><label>Description<textarea name="description" defaultValue={editingCategory.description} required maxLength="180" rows="4" /></label><div className="category-edit-summary"><span>Current status</span><strong>{editingCategory.status}</strong><span>Assigned questions</span><strong>{editingCategory.questions}</strong></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setEditingCategory(null)}>Cancel</button><button type="submit" className="primary-button">Save category</button></div></form></section></div>}
    {createCategoryOpen && <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setCreateCategoryOpen(false) }}><section className="confirmation-modal create-category-modal" role="dialog" aria-modal="true" aria-labelledby="create-category-title"><p className="eyebrow">Question organization</p><h2 id="create-category-title">Create a category</h2><p>New categories appear in operator question forms and archive filters.</p><form onSubmit={createCategory}><label>Category name<input name="name" required maxLength="40" placeholder="Example: Shipping & Delivery" /></label><label>Description<textarea name="description" required maxLength="180" rows="4" placeholder="Explain which questions belong here" /></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setCreateCategoryOpen(false)}>Cancel</button><button className="primary-button" type="submit">Create category</button></div></form></section></div>}
    {addAdminOpen && <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setAddAdminOpen(false) }}><section className="confirmation-modal add-admin-modal" role="dialog" aria-modal="true" aria-labelledby="add-admin-title"><p className="eyebrow">Super Admin action</p><h2 id="add-admin-title">Add an administrator</h2><p>Create an invitation for a trusted team member. They will set their password during activation.</p><form onSubmit={addAdmin}><label>Full name<input name="name" required autoComplete="name" /></label><label>Email address<input name="email" type="email" required autoComplete="email" placeholder="admin@example.com" /></label><label>Access level<select name="access" required><option>Moderator</option><option>Admin</option><option>Super Admin</option></select></label><div className="admin-permission-summary"><strong>Access summary</strong><p>Moderators manage content and escalations. Admins also manage users and categories. Super Admins can add other administrators.</p></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setAddAdminOpen(false)}>Cancel</button><button type="submit" className="primary-button">Send invitation</button></div></form></section></div>}
    <FeedbackModal open={Boolean(feedback)} title={feedback?.title} message={feedback?.message} onClose={() => setFeedback(null)} />
  </DashboardLayout>
}
