import { useEffect, useState } from 'react'
import { DashboardLayout } from '../components/DashboardLayout.jsx'
import { FeedbackModal } from '../components/FeedbackModal.jsx'
import { api, nextPaint } from '../lib/api.js'
const tabs=[{id:'overview',label:'Overview'},{id:'applications',label:'Expert approvals'},{id:'escalations',label:'Escalations'},{id:'moderation',label:'Moderation'},{id:'audit',label:'Audit activity'},{id:'categories',label:'Categories'},{id:'users',label:'User accounts'},{id:'admins',label:'Admin team'}]
export function AdminDashboard({user,onLogout}){
  const [tab,setTab]=useState('overview');const [apps,setApps]=useState([]);const [accounts,setAccounts]=useState([]);const [categories,setCategories]=useState([]);const [items,setItems]=useState([]);const [activity,setActivity]=useState([]);const [escalated,setEscalated]=useState([]);const [metrics,setMetrics]=useState({users:0,questions:0,experts:0,categories:[]});const [hours,setHours]=useState(24);const [feedback,setFeedback]=useState(null);const [userSearch,setUserSearch]=useState('');const [roleFilter,setRoleFilter]=useState('All roles');const [statusFilter,setStatusFilter]=useState('All statuses');const [editingCategory,setEditingCategory]=useState(null);const [createCategoryOpen,setCreateCategoryOpen]=useState(false);const [addAdminOpen,setAddAdminOpen]=useState(false)
  const load=()=>Promise.all([api('/admin/applications'),api('/admin/users'),api('/categories'),api('/admin/settings/escalation'),api('/admin/moderation'),api('/admin/audit'),api('/admin/escalations'),api('/admin/dashboard')]).then(([applications,users,categoryItems,setting,moderation,audit,escalations,dashboard])=>{setApps(applications.map(x=>({...x,name:x.user.name,score:x.user.reputation,status:x.status==='PENDING'?'Pending review':x.status[0]+x.status.slice(1).toLowerCase()})));setAccounts(users.map(x=>({...x,role:x.role==='EXPERT'?'Verified Expert':x.role==='ADMIN'?'Administrator':'Operator',status:x.isActive?'Active':'Suspended',lastSeen:new Date(x.lastSeenAt).toLocaleString()})));setCategories(categoryItems.map(x=>({...x,status:x.isActive?'Active':'Inactive'})));setHours(setting.hours);setItems(moderation);setActivity(audit);setEscalated(escalations);setMetrics(dashboard)})
  useEffect(()=>{load().catch(error=>setFeedback({title:'Admin data could not be loaded',message:error.message}))},[])
  const action=async(work,success,optimistic)=>{try{const result=await work();if(typeof optimistic==='function')optimistic(result);await nextPaint();setFeedback(success);load().catch(()=>{})}catch(error){setFeedback({title:'Action failed',message:error.message})}}
  const review=(item,status)=>{const title=item.status==='Pending review'?(status==='APPROVED'?'Application approved':'Application rejected'):(status==='APPROVED'?'Expert access restored':'Expert access deactivated');return action(()=>api(`/admin/applications/${item.id}`,{method:'PATCH',body:JSON.stringify({status})}),{title,message:`${item.name}'s verification status was updated.`},()=>setApps(current=>current.map(application=>application.id===item.id?{...application,status:status==='APPROVED'?'Approved':'Rejected'}:application)))}
  const toggleAccount=account=>action(()=>api(`/admin/users/${account.id}/status`,{method:'PATCH',body:JSON.stringify({isActive:account.status!=='Active'})}),{title:account.status==='Active'?'Account deactivated':'Account restored',message:`${account.name}'s access was updated.`},()=>setAccounts(current=>current.map(item=>item.id===account.id?{...item,status:account.status==='Active'?'Suspended':'Active'}:item)))
  const resolveItem=item=>action(()=>api(`/admin/moderation/${item.id}/resolve`,{method:'PATCH',body:JSON.stringify({resolution:'Resolved by administrator'})}),{title:'Moderation resolved',message:'The queue and audit log were updated.'},()=>setItems(current=>current.filter(entry=>entry.id!==item.id)))
  const notifyExperts=question=>action(()=>api(`/admin/escalations/${question.id}/notify`,{method:'POST'}),{title:'Experts notified',message:'Available verified experts received a notification.'})
  const saveHours=async value=>{setHours(value);try{await api('/admin/settings/escalation',{method:'PATCH',body:JSON.stringify({hours:value})})}catch(error){setFeedback({title:'Setting could not be saved',message:error.message})}}
  const createCategory=event=>{event.preventDefault();const data=new FormData(event.currentTarget);action(()=>api('/categories',{method:'POST',body:JSON.stringify({name:data.get('name').trim(),description:data.get('description').trim()})}),{title:'Category created',message:'The category is available for new questions.'},created=>setCategories(current=>[...current,{...created,status:'Active',questions:0}]));setCreateCategoryOpen(false)}
  const saveCategory=event=>{event.preventDefault();const data=new FormData(event.currentTarget);action(()=>api(`/categories/${editingCategory.id}`,{method:'PATCH',body:JSON.stringify({name:data.get('name').trim(),description:data.get('description').trim(),isActive:editingCategory.isActive})}),{title:'Category updated',message:'The category was saved.'},updated=>setCategories(current=>current.map(item=>item.id===updated.id?{...item,...updated,status:updated.isActive?'Active':'Inactive'}:item)));setEditingCategory(null)}
  const toggleCategory=category=>action(()=>api(`/categories/${category.id}`,{method:'PATCH',body:JSON.stringify({name:category.name,description:category.description,isActive:!category.isActive})}),{title:'Category updated',message:`${category.name} is now ${category.isActive?'inactive':'active'}.`},()=>setCategories(current=>current.map(item=>item.id===category.id?{...item,isActive:!category.isActive,status:category.isActive?'Inactive':'Active'}:item)))
  const removeCategory=category=>action(()=>api(`/categories/${category.id}`,{method:'DELETE'}),{title:'Category removed',message:`${category.name} was removed.`},()=>setCategories(current=>current.filter(item=>item.id!==category.id)))
  const addAdmin=event=>{event.preventDefault();const data=new FormData(event.currentTarget);action(()=>api('/admin/users/admin',{method:'POST',body:JSON.stringify({name:data.get('name').trim(),email:data.get('email').trim(),password:data.get('password')})}),{title:'Administrator created',message:'The administrator can log in with the temporary password.'},'Creating administrator…');setAddAdminOpen(false)}
  const pending=apps.filter(x=>x.status==='Pending review').length;const admins=accounts.filter(x=>x.role==='Administrator');const filteredUsers=accounts.filter(x=>`${x.name} ${x.email}`.toLowerCase().includes(userSearch.toLowerCase())&&(roleFilter==='All roles'||x.role===roleFilter)&&(statusFilter==='All statuses'||x.status===statusFilter));const totalCategoryQuestions=Math.max(1,metrics.categories.reduce((sum,x)=>sum+x.questions,0))
  return <DashboardLayout user={user} onLogout={onLogout} title={tab==='overview'?'Operations overview':tabs.find(x=>x.id===tab).label} subtitle="Keep support responsive, safe, and accountable." tabs={tabs} activeTab={tab} onTabChange={setTab}>
    {tab==='overview'&&<><section className="admin-command-banner"><div><p className="eyebrow">Platform command center</p><h2>Everything that needs attention, in one place.</h2><p>{metrics.questions} questions across {metrics.users} registered accounts.</p></div><div className="admin-health"><span className="health-ring"><strong>{hours}h</strong><small>SLA</small></span><div><strong>Escalation threshold</strong><p>Unanswered questions are tracked for action.</p></div></div></section><div className="admin-metric-grid"><button onClick={()=>setTab('escalations')}><div><small>Needs attention</small><strong>{escalated.length}</strong><span>Unanswered questions</span></div></button><button onClick={()=>setTab('applications')}><div><small>Awaiting review</small><strong>{pending}</strong><span>Expert applications</span></div></button><button onClick={()=>setTab('moderation')}><div><small>Content safety</small><strong>{items.length}</strong><span>Moderation items</span></div></button><button onClick={()=>setTab('users')}><div><small>Community accounts</small><strong>{metrics.users}</strong><span>Registered users</span></div></button></div><div className="admin-overview-grid"><section className="panel"><h4>Requires admin attention</h4>{escalated.slice(0,5).map(q=><article className="admin-priority-row" key={q.id}><div><strong>{q.title}</strong><p>{q.category} · {new Date(q.createdAt).toLocaleString()}</p></div><span className="status-badge critical">{q.status}</span><button className="secondary-button compact" onClick={()=>notifyExperts(q)}>Notify experts</button></article>)}</section><section className="panel admin-activity"><h4>Recent audit activity</h4><div className="activity-timeline">{activity.map(item=><article key={item.id}><div><strong>{item.action.replaceAll('_',' ')}</strong><p>{item.detail}</p></div><time>{new Date(item.createdAt).toLocaleString()}</time></article>)}</div></section></div><div className="admin-insight-grid"><section className="panel"><h4>Questions by category</h4><div className="category-bars">{metrics.categories.map(item=><div key={item.name}><span><strong>{item.name}</strong><small>{item.questions}</small></span><i><b style={{width:`${item.questions/totalCategoryQuestions*100}%`}}/></i></div>)}</div></section><section className="panel"><h4>Verified pool health</h4><div className="coverage-summary"><strong>{metrics.experts}</strong><span>approved experts</span></div></section></div></>}
    {tab==='applications'&&<section className="panel admin-table-panel"><h4>Expert application queue</h4><div className="table-wrap"><table><thead><tr><th>Applicant</th><th>Specialty</th><th>Reputation</th><th>Status</th><th>Decision</th></tr></thead><tbody>{apps.map(item=><tr key={item.id}><td>{item.name}</td><td>{item.specialty}</td><td>{item.score}</td><td><span className={`status-badge ${item.status==='Rejected'?'critical':'normal'}`}>{item.status}</span></td><td>{item.status==='Pending review'?<div className="approval-buttons"><button className="text-button" onClick={()=>review(item,'APPROVED')}>Approve</button><button className="text-button danger" onClick={()=>review(item,'REJECTED')}>Reject</button></div>:item.status==='Approved'?<button className="text-button danger" onClick={()=>review(item,'REJECTED')}>Deactivate</button>:<button className="text-button" onClick={()=>review(item,'APPROVED')}>Restore</button>}</td></tr>)}</tbody></table></div></section>}
    {tab==='escalations'&&<div className="admin-settings-layout"><section className="panel"><h4>Escalation queue</h4>{escalated.map(q=><div className="queue-item" key={q.id}><div><strong>{q.title}</strong><p>{q.category} · {new Date(q.createdAt).toLocaleString()}</p></div><button className="secondary-button compact" onClick={()=>notifyExperts(q)}>Notify experts</button></div>)}</section><aside className="panel escalation-setting"><h4>Automatic escalation</h4><label>Threshold: {hours} hours<input type="range" min="6" max="48" step="6" value={hours} onChange={e=>saveHours(Number(e.target.value))}/></label></aside></div>}
    {tab==='moderation'&&<section className="panel"><h4>Moderation queue</h4>{items.length?items.map(item=><article className="moderation-card" key={item.id}><div><strong>{item.subject}</strong><p>{item.detail}</p><small>{item.kind} · {new Date(item.createdAt).toLocaleString()}</small></div><button className="text-button danger" onClick={()=>resolveItem(item)}>Resolve item</button></article>):<div className="empty-state"><strong>Queue is clear</strong></div>}</section>}
    {tab==='categories'&&<section className="panel category-list-panel"><div className="board-toolbar"><h4>Support categories</h4><button className="primary-button" onClick={()=>setCreateCategoryOpen(true)}>Create category</button></div><div className="category-admin-list">{categories.map(item=><article key={item.id}><div><strong>{item.name}</strong><p>{item.description}</p><small>{item.questions} questions</small></div><span>{item.status}</span><div><button className="text-button" onClick={()=>setEditingCategory(item)}>Edit</button><button className="text-button" onClick={()=>toggleCategory(item)}>{item.isActive?'Deactivate':'Activate'}</button><button className="text-button danger" onClick={()=>removeCategory(item)}>Remove</button></div></article>)}</div></section>}
    {tab==='users'&&<section className="panel admin-table-panel"><div className="user-filter-bar"><input placeholder="Search users" value={userSearch} onChange={e=>setUserSearch(e.target.value)}/><select value={roleFilter} onChange={e=>setRoleFilter(e.target.value)}><option>All roles</option><option>Operator</option><option>Verified Expert</option><option>Administrator</option></select><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option>All statuses</option><option>Active</option><option>Suspended</option></select></div><div className="table-wrap"><table><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Last seen</th><th>Action</th></tr></thead><tbody>{filteredUsers.map(item=><tr key={item.id}><td><strong>{item.name}</strong><small className="table-subtext">{item.email}</small></td><td>{item.role}</td><td>{item.status}</td><td>{item.lastSeen}</td><td><button className="text-button" onClick={()=>toggleAccount(item)}>{item.status==='Active'?'Suspend':'Restore'}</button></td></tr>)}</tbody></table></div></section>}
    {tab==='admins'&&<section className="panel admin-team-panel"><div className="board-toolbar"><h4>Administrator team</h4><button className="primary-button" onClick={()=>setAddAdminOpen(true)}>Add admin</button></div><div className="table-wrap"><table><tbody>{admins.map(item=><tr key={item.id}><td><strong>{item.name}</strong><small className="table-subtext">{item.email}</small></td><td>{item.email===user.email?'Super Admin':'Admin'}</td><td>{item.status}</td><td>{item.email!==user.email&&<button className="text-button danger" onClick={()=>toggleAccount(item)}>{item.status==='Active'?'Deactivate':'Restore'}</button>}</td></tr>)}</tbody></table></div></section>}
    {createCategoryOpen&&<div className="modal-backdrop"><section className="confirmation-modal"><h2>Create category</h2><form onSubmit={createCategory}><label>Name<input name="name" required/></label><label>Description<textarea name="description" required minLength="5"/></label><div className="modal-actions"><button type="button" onClick={()=>setCreateCategoryOpen(false)}>Cancel</button><button className="primary-button">Create</button></div></form></section></div>}
    {editingCategory&&<div className="modal-backdrop"><section className="confirmation-modal"><h2>Edit category</h2><form onSubmit={saveCategory}><label>Name<input name="name" defaultValue={editingCategory.name} required/></label><label>Description<textarea name="description" defaultValue={editingCategory.description} required/></label><div className="modal-actions"><button type="button" onClick={()=>setEditingCategory(null)}>Cancel</button><button className="primary-button">Save</button></div></form></section></div>}
    {addAdminOpen&&<div className="modal-backdrop"><section className="confirmation-modal"><h2>Add administrator</h2><form onSubmit={addAdmin}><label>Name<input name="name" required/></label><label>Email<input name="email" type="email" required/></label><label>Temporary password<input name="password" type="password" minLength="8" required/></label><div className="modal-actions"><button type="button" onClick={()=>setAddAdminOpen(false)}>Cancel</button><button className="primary-button">Create admin</button></div></form></section></div>}
    {tab==='audit'&&<section className="panel admin-audit-panel"><div className="board-toolbar"><div><p className="eyebrow">Platform history</p><h4>All audit activity</h4><p>Review administrative and user actions across the platform.</p></div><span className="pill">{activity.length} events</span></div>{activity.length?<div className="activity-timeline audit-full-list">{activity.map(item=><article key={item.id}><span aria-hidden="true"/><div><strong>{item.action.replaceAll('_',' ')}</strong><p>{item.detail}</p>{item.actor?.name&&<small>By {item.actor.name}</small>}</div><time>{new Date(item.createdAt).toLocaleString()}</time></article>)}</div>:<div className="empty-state"><strong>No audit activity yet</strong><p>Platform actions will appear here.</p></div>}</section>}
    <FeedbackModal open={Boolean(feedback)} title={feedback?.title} message={feedback?.message} onClose={()=>setFeedback(null)}/>
  </DashboardLayout>
}
