import { useState } from 'react'
import { DashboardLayout } from '../components/DashboardLayout.jsx'
import { expertApplications, initialQuestions, moderationQueue, userAccounts } from '../data/platformData.js'
const tabs=[{id:'overview',label:'Overview'},{id:'applications',label:'Expert approvals'},{id:'escalations',label:'Escalations'},{id:'moderation',label:'Moderation'},{id:'users',label:'User accounts'}]
export function AdminDashboard({user,onLogout}){
 const [tab,setTab]=useState('overview');const [apps,setApps]=useState(expertApplications);const [items,setItems]=useState(moderationQueue);const [accounts,setAccounts]=useState(userAccounts);const [hours,setHours]=useState(24)
 const review=(name,status)=>setApps(xs=>xs.map(x=>x.name===name?{...x,status}:x));const toggle=(name)=>setAccounts(xs=>xs.map(x=>x.name===name?{...x,status:x.status==='Suspended'?'Active':'Suspended'}:x))
 return <DashboardLayout user={user} onLogout={onLogout} title={tabs.find(x=>x.id===tab).label} subtitle="Keep support responsive, safe, and accountable." tabs={tabs} activeTab={tab} onTabChange={setTab}>
  {tab==='overview'&&<><div className="dashboard-stats"><article><span>Unanswered</span><strong>7</strong></article><article><span>Escalated</span><strong>3</strong></article><article><span>Pending experts</span><strong>{apps.filter(x=>x.status==='Pending review').length}</strong></article></div><div className="dashboard-grid"><section className="panel"><h4>Needs attention</h4>{items.map(x=><div className="queue-item" key={x.id}><div><strong>{x.applicant}</strong><p>{x.specialty}</p></div><span className="pill">{x.decision}</span></div>)}</section><section className="panel"><h4>Platform health</h4><div className="profile-metrics"><article><strong>96%</strong><span>answered within SLA</span></article><article><strong>4.8/5</strong><span>helpfulness</span></article><article><strong>142</strong><span>active experts</span></article></div></section></div></>}
  {tab==='applications'&&<section className="panel"><h4>Expert application queue</h4><div className="table-wrap"><table><thead><tr><th>Applicant</th><th>Specialty</th><th>Score</th><th>Status</th><th>Decision</th></tr></thead><tbody>{apps.map(x=><tr key={x.name}><td>{x.name}</td><td>{x.specialty}</td><td>{x.score}</td><td>{x.status}</td><td><div className="approval-buttons"><button className="text-button" onClick={()=>review(x.name,'Approved')}>Approve</button><button className="text-button danger" onClick={()=>review(x.name,'Rejected')}>Reject</button></div></td></tr>)}</tbody></table></div></section>}
  {tab==='escalations'&&<section className="panel"><label>Automatic escalation threshold: {hours} hours<input type="range" min="6" max="48" step="6" value={hours} onChange={e=>setHours(Number(e.target.value))}/></label><p>Unanswered questions notify additional experts and admins after this threshold.</p>{initialQuestions.filter(x=>x.escalated||x.responses===0).map(x=><div className="queue-item" key={x.id}><div><strong>{x.title}</strong><p>{x.category} · {x.age}</p></div><button className="secondary-button compact">Notify experts</button></div>)}</section>}
  {tab==='moderation'&&<section className="panel"><h4>Flagged content</h4>{items.map(x=><div className="queue-item" key={x.id}><div><strong>{x.applicant}</strong><p>{x.specialty}</p></div><button className="text-button danger" onClick={()=>setItems(xs=>xs.filter(i=>i.id!==x.id))}>{x.id.startsWith('MOD')?'Remove content':'Resolve item'}</button></div>)}</section>}
  {tab==='users'&&<section className="panel"><h4>All user accounts</h4><div className="table-wrap"><table><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Last seen</th><th>Action</th></tr></thead><tbody>{accounts.map(x=><tr key={x.name}><td>{x.name}</td><td>{x.role}</td><td>{x.status}</td><td>{x.lastSeen}</td><td><button className="text-button" onClick={()=>toggle(x.name)}>{x.status==='Suspended'?'Restore':'Suspend'}</button></td></tr>)}</tbody></table></div></section>}
 </DashboardLayout>
}
