import { useState } from 'react'
import authVisual from '../assets/auth-support-network.png'

export function AuthPage({ mode, onAuthenticate, navigate, notice = '' }) {
  const signingUp = mode === 'signup'
  const [role, setRole] = useState('operator')
  const roleOptions = signingUp ? [['operator','Get help'],['expert','Give help'],['both','Both']] : [['operator','Get help'],['expert','Give help'],['admin','Admin access']]
  const submit = (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); onAuthenticate({ name: data.get('name') || data.get('email').split('@')[0], email: data.get('email'), role: role === 'both' ? 'operator' : role, intent: role }) }
  return <div className="auth-shell"><section className="auth-story"><img className="auth-story-image" src={authVisual} alt="A store owner connected to a welcoming network of verified e-commerce support experts" /><div className="auth-story-shade" aria-hidden="true" /><button className="brand-button auth-story-content" onClick={() => navigate('/')}><span className="brand-mark">E</span><span>E-Com Support</span></button><div className="auth-story-content"><p className="eyebrow">Community-powered support</p><h1>{signingUp ? 'Get the right help, faster.' : 'Welcome back.'}</h1><p>Connect with verified e-commerce experts, track every request, and keep proven answers easy to find.</p></div><div className="auth-proof auth-story-content"><strong>No question gets ignored.</strong><span>Unanswered requests are automatically escalated.</span></div></section>
    <main className="auth-card"><div><p className="eyebrow">{signingUp ? 'Create your account' : 'Secure access'}</p><h2>{signingUp ? 'Join E-Com Support' : 'Log in to your dashboard'}</h2><p>{signingUp ? 'Choose the role that best describes you.' : 'Select your role and enter your account details.'}</p></div>{notice && <p className="auth-notice" role="alert">{notice}</p>}
      <form onSubmit={submit}>{signingUp && <label>Full name<input name="name" autoComplete="name" required /></label>}<label>Email address<input name="email" type="email" autoComplete="email" required placeholder="you@example.com" /></label><label>Password<input name="password" type="password" autoComplete={signingUp ? 'new-password' : 'current-password'} minLength="8" required /></label><fieldset><legend>{signingUp ? 'Are you here to get help, give help, or both?' : 'How are you using the platform?'}</legend><div className={`auth-role-grid ${signingUp ? 'two-options' : ''}`}>{roleOptions.map(([value,label]) => <label className={role === value ? 'selected' : ''} key={value}><input type="radio" name="role" value={value} checked={role === value} onChange={() => setRole(value)} /><span>{label}</span></label>)}</div></fieldset><button className="primary-button" type="submit">{signingUp ? 'Create account' : 'Log in'}</button></form>
      <p className="auth-switch">{signingUp ? 'Already have an account?' : 'New to the platform?'} <button className="text-button" onClick={() => navigate(signingUp ? '/login' : '/signup')}>{signingUp ? 'Log in' : 'Create account'}</button></p>
    </main></div>
}
