import { useState } from 'react'
import authVisual from '../assets/auth-support-network.png'
import { api, normalizeUser } from '../lib/api.js'

export function AuthPage({ mode, onAuthenticate, navigate, notice = '', adminMode = false }) {
  const signingUp = mode === 'signup'
  const [role, setRole] = useState('operator')
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(false)
  const [recovery,setRecovery]=useState(false);const [resetToken,setResetToken]=useState('')
  const submit = async (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); setError(''); setLoading(true)
    try {
      const result = await api(signingUp ? '/auth/register' : '/auth/login', { method: 'POST', body: JSON.stringify(signingUp ? { name: data.get('name'), email: data.get('email'), password: data.get('password'), role: role.toUpperCase() } : { email: data.get('email'), password: data.get('password') }) })
      const user = normalizeUser(result.user)
      if (adminMode && user.role !== 'admin') throw new Error('This account does not have administrator access.')
      if (signingUp && role === 'expert' && user.role !== 'expert') user.verificationStatus = 'pending'
      onAuthenticate({ ...user, accessToken: result.accessToken })
    } catch (requestError) { setError(requestError.message) }
    finally { setLoading(false) }
  }
  const recover=async event=>{event.preventDefault();const data=new FormData(event.currentTarget);setLoading(true);setError('');try{if(!resetToken){const result=await api('/auth/forgot-password',{method:'POST',body:JSON.stringify({email:data.get('email')})});setResetToken(result.resetToken||'requested')}else{await api('/auth/reset-password',{method:'POST',body:JSON.stringify({token:resetToken,password:data.get('password')})});setRecovery(false);setResetToken('');setError('Password reset successfully. You can now log in.')}}catch(requestError){setError(requestError.message)}finally{setLoading(false)}}
  if(recovery)return <div className="auth-shell"><section className="auth-story"><img className="auth-story-image" src={authVisual} alt="Support account recovery"/><div className="auth-story-shade"/><button className="brand-button auth-story-content" onClick={()=>navigate('/')}><span className="brand-mark">E</span><span>E-Com Support</span></button></section><main className="auth-card"><div><p className="eyebrow">Account recovery</p><h2>{resetToken?'Choose a new password':'Reset your password'}</h2><p>{resetToken?'Enter a secure new password for your account.':'Enter the email attached to your account.'}</p></div><form onSubmit={recover}>{!resetToken?<label>Email address<input name="email" type="email" required autoFocus/></label>:<label>New password<input name="password" type="password" minLength="8" required autoFocus/></label>}{error&&<p className="auth-notice" role="alert">{error}</p>}<button className="primary-button" disabled={loading}>{loading?'Please wait…':resetToken?'Reset password':'Continue'}</button></form><button className="text-button" onClick={()=>{setRecovery(false);setResetToken('');setError('')}}>Back to login</button></main></div>
  return <div className="auth-shell"><section className="auth-story"><img className="auth-story-image" src={authVisual} alt="A store owner connected to a welcoming network of verified e-commerce support experts"/><div className="auth-story-shade" aria-hidden="true"/><button className="brand-button auth-story-content" onClick={() => navigate('/')}><span className="brand-mark">E</span><span>E-Com Support</span></button><div className="auth-story-content"><p className="eyebrow">{adminMode ? 'Restricted access' : 'Community-powered support'}</p><h1>{adminMode ? 'Administration.' : signingUp ? 'Get the right help, faster.' : 'Welcome back.'}</h1><p>{adminMode ? 'Authorized platform administrators only.' : 'Connect with verified people, track every request, and keep proven answers easy to find.'}</p></div></section>
    <main className="auth-card"><div><p className="eyebrow">{signingUp ? 'Create your account' : 'Secure access'}</p><h2>{adminMode ? 'Admin login' : signingUp ? 'Join E-Com Support' : 'Log in to your account'}</h2><p>{signingUp ? 'Choose what you want to do first. You can change views later.' : 'Enter your account details to continue.'}</p></div>{notice && <p className="auth-notice" role="alert">{notice}</p>}
      <form onSubmit={submit}>{signingUp && <label>Full name<input name="name" autoComplete="name" required/></label>}<label>Email address<input name="email" type="email" autoComplete="email" required placeholder="you@example.com"/></label><label>Password<input name="password" type="password" autoComplete={signingUp ? 'new-password' : 'current-password'} minLength="8" required/></label>{signingUp && <fieldset><legend>What brings you here?</legend><div className="auth-role-grid two-options">{[['operator','I need help'],['expert','I want to give help']].map(([value,label]) => <label className={role === value ? 'selected' : ''} key={value}><input type="radio" name="role" value={value} checked={role === value} onChange={() => setRole(value)}/><span>{label}</span></label>)}</div></fieldset>}{error && <p className="auth-notice" role="alert">{error}</p>}<button className="primary-button" type="submit" disabled={loading}>{loading ? 'Please wait…' : signingUp ? 'Create account' : 'Log in'}</button></form>
      {!adminMode && <><p className="auth-switch">{signingUp ? 'Already have an account?' : 'New to the platform?'} <button className="text-button" onClick={() => navigate(signingUp ? '/login' : '/signup')}>{signingUp ? 'Log in' : 'Create account'}</button></p>{!signingUp&&<button className="text-button auth-recovery-link" onClick={()=>{setRecovery(true);setError('')}}>Forgot password?</button>}</>}
    </main></div>
}
