import { useState } from 'react'
import { DashboardLayout } from '../components/DashboardLayout.jsx'
import { FeedbackModal } from '../components/FeedbackModal.jsx'
import { initialQuestions, pointEvents } from '../data/platformData.js'
const tabs = [{id:'queue',label:'Question queue'},{id:'answers',label:'My answers'},{id:'profile',label:'Public profile'},{id:'application',label:'Verification'},{id:'notifications',label:'Notifications'}]
export function ExpertDashboard({ user, onLogout }) {
  const [tab,setTab]=useState('queue'); const [selected,setSelected]=useState(null); const [feedback,setFeedback]=useState(null); const [application,setApplication]=useState('Approved'); const [specialties,setSpecialties]=useState(['Checkout']); const [points,setPoints]=useState(1248); const [answerCount,setAnswerCount]=useState(48); const [notifications,setNotifications]=useState([{id:1,title:'Answer accepted',detail:'Your mobile checkout answer earned a 35-point bonus.',time:'12 min ago',unread:true},{id:2,title:'New question in Checkout',detail:'A high-priority mobile checkout issue matches your specialty.',time:'28 min ago',unread:true},{id:3,title:'Community upvote',detail:'Your theme layout answer earned 5 reputation points.',time:'2 hr ago',unread:false}])
  const toggleSpecialty=(specialty)=>setSpecialties((current)=>current.includes(specialty)?current.filter((item)=>item!==specialty):[...current,specialty])
  const answer=(event)=>{event.preventDefault();setPoints((value)=>value+20);setAnswerCount((value)=>value+1);setNotifications((items)=>[{id:Date.now(),title:'Answer posted',detail:'20 base reputation points were added.',time:'Just now',unread:true},...items]);setFeedback({title:'Answer posted successfully',message:'The operator has been notified and 20 base points were added to your reputation.'});setSelected(null)}
  const updateApplication=()=>{setApplication('Submitted for review');setFeedback({title:'Application submitted for review',message:'Answering access is paused while an administrator reviews your updated specialties and experience.'})}
  return <DashboardLayout user={user} onLogout={onLogout} title={tabs.find(x=>x.id===tab).label} subtitle="Share reliable answers and build your reputation." tabs={tabs} activeTab={tab} onTabChange={setTab}>
    <div className="dashboard-stats"><article><span>Reputation points</span><strong>{points.toLocaleString()}</strong></article><article><span>Accepted rate</span><strong>94%</strong></article><article><span>Average response</span><strong>12m</strong></article></div>
    {tab==='queue'&&(application==='Approved'?<div className="dashboard-grid"><section className="panel"><div className="board-toolbar"><h4>Open and unanswered questions</h4><span className="status-badge normal">Verified access</span></div>{initialQuestions.map(q=><button className={`question-list-button ${selected?.id===q.id?'active':''}`} key={q.id} onClick={()=>setSelected(q)}><span><strong>{q.title}</strong><small>{q.category} · {q.age}</small></span><span className={`status-badge ${q.escalated?'critical':'normal'}`}>{q.urgency}</span></button>)}</section><section className="panel">{selected?<form className="form-card embedded" onSubmit={answer}><div><span className="pill">{selected.category}</span><h4>{selected.title}</h4><p>Respond in simple language and include clear steps the operator can follow.</p></div><label>Your verified answer<textarea required placeholder="Explain the cause and recommended solution" /></label><button className="primary-button">Post answer</button></form>:<div className="empty-state"><strong>Select a question</strong><p>Choose an issue from the queue to review and answer it.</p></div>}</section></div>:<section className="panel verification-gate"><span className="feature-icon" aria-hidden="true">⌛</span><h4>Verification review in progress</h4><p>Only approved experts can browse and answer open questions. We’ll notify you as soon as an administrator completes the review.</p><button className="secondary-button" onClick={()=>setTab('application')}>View application status</button></section>)}
    {tab==='answers'&&<section className="panel"><h4>Response history</h4><div className="table-wrap"><table><thead><tr><th>Question</th><th>Status</th><th>Points</th><th>Helpful votes</th></tr></thead><tbody><tr><td>Mobile checkout overlay issue</td><td><span className="status-badge normal">Accepted</span></td><td>+85</td><td>18</td></tr><tr><td>Theme header overlap</td><td>Answered</td><td>+40</td><td>4</td></tr></tbody></table></div></section>}
    {tab==='profile'&&<><section className="public-profile-preview"><div className="public-profile-cover"><span className="status-badge normal">Public profile</span></div><div className="public-profile-body"><span className="public-avatar">{user.name[0]}</span><div><h3>{user.name}</h3><p>Verified e-commerce expert · {specialties.join(' · ')}</p></div><button className="secondary-button" onClick={()=>setFeedback({title:'Public profile link copied',message:'Your shareable profile link is ready to send to operators and clients.'})}>Share profile</button></div><div className="profile-metrics"><article><strong>{points.toLocaleString()}</strong><span>reputation points</span></article><article><strong>94%</strong><span>accepted answers</span></article><article><strong>312</strong><span>community upvotes</span></article><article><strong>{answerCount}</strong><span>answers posted</span></article></div><div className="public-history"><h4>Recent public answer history</h4><article><div><strong>Mobile checkout overlay issue</strong><p>Checkout · Accepted solution</p></div><span>18 helpful</span></article><article><div><strong>Theme header overlap on tablet</strong><p>Theme / Design · Answered</p></div><span>4 helpful</span></article></div></section><section className="panel points-panel compact-points"><h4>How points work</h4><div className="point-list">{pointEvents.map(item=><div className="point-item" key={item.label}><strong>{item.label}</strong><span>{item.value}</span></div>)}</div></section></>}
    {tab==='application'&&<section className="panel dashboard-form expert-application-form"><span className="status-badge normal">{application}</span><h4>Expert verification</h4><p>Experts must be reviewed and approved before answers receive a verified label.</p><fieldset className="specialty-fieldset"><legend>Areas of specialty <small>Select all that apply</small></legend><div className="specialty-options">{['Checkout','Payments','Theme / Design','Apps'].map((specialty)=><label className={specialties.includes(specialty)?'selected':''} key={specialty}><input type="checkbox" checked={specialties.includes(specialty)} onChange={()=>toggleSpecialty(specialty)} /><span className="specialty-check" aria-hidden="true">✓</span><span>{specialty}</span></label>)}</div></fieldset><label>Professional experience<textarea placeholder="Describe your relevant experience" /></label><button className="primary-button application-submit" disabled={specialties.length===0} onClick={updateApplication}>Update application</button></section>}
    {tab==='notifications'&&<section className="panel notification-center"><div className="board-toolbar"><div><p className="eyebrow">Expert activity</p><h4>Notifications</h4><p>Reputation, verification, and matching question updates.</p></div><button className="text-button" onClick={()=>setNotifications((items)=>items.map((item)=>({...item,unread:false})))}>Mark all as read</button></div>{notifications.map((item)=><article className={`notification-row ${item.unread?'unread':''}`} key={item.id}><span className="notification-dot" aria-hidden="true"/><div><strong>{item.title}</strong><p>{item.detail}</p></div><time>{item.time}</time></article>)}</section>}
    <FeedbackModal open={Boolean(feedback)} title={feedback?.title} message={feedback?.message} onClose={()=>setFeedback(null)} />
  </DashboardLayout>
}
