import { useState } from 'react'
import { DashboardLayout } from '../components/DashboardLayout.jsx'
import { initialQuestions, pointEvents } from '../data/platformData.js'
const tabs = [{id:'queue',label:'Question queue'},{id:'answers',label:'My answers'},{id:'profile',label:'Public profile'},{id:'application',label:'Verification'}]
export function ExpertDashboard({ user, onLogout }) {
  const [tab,setTab]=useState('queue'); const [selected,setSelected]=useState(null); const [notice,setNotice]=useState(''); const [application,setApplication]=useState('Pending review')
  const answer=(event)=>{event.preventDefault();setNotice('Verified answer posted. You earned 20 base points.');setSelected(null)}
  return <DashboardLayout user={user} onLogout={onLogout} title={tabs.find(x=>x.id===tab).label} subtitle="Share reliable answers and build your reputation." tabs={tabs} activeTab={tab} onTabChange={setTab}>
    <div className="dashboard-stats"><article><span>Reputation points</span><strong>1,248</strong></article><article><span>Accepted rate</span><strong>94%</strong></article><article><span>Average response</span><strong>12m</strong></article></div>
    {notice&&<p className="success-notice" role="status">{notice}</p>}
    {tab==='queue'&&<div className="dashboard-grid"><section className="panel"><h4>Open and unanswered questions</h4>{initialQuestions.map(q=><button className={`question-list-button ${selected?.id===q.id?'active':''}`} key={q.id} onClick={()=>setSelected(q)}><span><strong>{q.title}</strong><small>{q.category} · {q.age}</small></span><span className={`status-badge ${q.escalated?'critical':'normal'}`}>{q.urgency}</span></button>)}</section><section className="panel">{selected?<form className="form-card embedded" onSubmit={answer}><div><span className="pill">{selected.category}</span><h4>{selected.title}</h4><p>Respond in simple language and include clear steps the operator can follow.</p></div><label>Your verified answer<textarea required placeholder="Explain the cause and recommended solution" /></label><button className="primary-button">Post answer</button></form>:<div className="empty-state"><strong>Select a question</strong><p>Choose an issue from the queue to review and answer it.</p></div>}</section></div>}
    {tab==='answers'&&<section className="panel"><h4>Response history</h4><div className="table-wrap"><table><thead><tr><th>Question</th><th>Status</th><th>Points</th><th>Helpful votes</th></tr></thead><tbody><tr><td>Mobile checkout overlay issue</td><td><span className="status-badge normal">Accepted</span></td><td>+85</td><td>18</td></tr><tr><td>Theme header overlap</td><td>Answered</td><td>+40</td><td>4</td></tr></tbody></table></div></section>}
    {tab==='profile'&&<div className="dashboard-grid"><section className="panel"><div className="profile-card"><div><p className="profile-name">{user.name}</p><p>Verified expert · Checkout flows</p></div><div className="profile-score"><strong>1,248</strong><span>points</span></div></div><div className="profile-metrics"><article><strong>94%</strong><span>accepted</span></article><article><strong>312</strong><span>upvotes</span></article><article><strong>48</strong><span>answers</span></article></div></section><section className="panel"><h4>How points work</h4>{pointEvents.map(item=><div className="point-item" key={item.label}><strong>{item.label}</strong><span>{item.value}</span></div>)}</section></div>}
    {tab==='application'&&<section className="panel dashboard-form"><span className="status-badge normal">{application}</span><h4>Expert verification</h4><p>Experts must be reviewed and approved before answers receive a verified label.</p><label>Primary specialty<select><option>Checkout</option><option>Payments</option><option>Theme / Design</option><option>Apps</option></select></label><label>Professional experience<textarea placeholder="Describe your relevant experience" /></label><button className="primary-button" onClick={()=>setApplication('Submitted for review')}>Update application</button></section>}
  </DashboardLayout>
}
