import { useEffect, useState } from 'react'
import { DashboardLayout } from '../components/DashboardLayout.jsx'
import { FeedbackModal } from '../components/FeedbackModal.jsx'
import { pointEvents } from '../data/platformData.js'
import { api } from '../lib/api.js'

const tabs = [{id:'queue',label:'Question queue'},{id:'answers',label:'My answers'},{id:'profile',label:'Public profile'},{id:'application',label:'Verification'}]

export function ExpertDashboard({ user, onLogout, onSwitchView }) {
  const [tab,setTab]=useState('queue'); const [selected,setSelected]=useState(null); const [feedback,setFeedback]=useState(null)
  const [application,setApplication]=useState('Application required'); const [specialties,setSpecialties]=useState(['Checkout'])
  const [points,setPoints]=useState(user.reputation || 0); const [answers,setAnswers]=useState([]); const [questions,setQuestions]=useState([])
  const load=()=>Promise.all([api('/questions'),api('/questions/answers/mine'),api('/expert-applications/me')]).then(([queue,history,app])=>{setQuestions(queue);setAnswers(history);if(app){setApplication(app.status==='APPROVED'?'Approved':app.status==='REJECTED'?'Rejected':'Submitted for review');setSpecialties(app.specialty.split(', ').filter(Boolean))}})
  useEffect(()=>{load().catch(error=>setFeedback({title:'Could not load expert workspace',message:error.message}))},[])
  const toggleSpecialty=(specialty)=>setSpecialties(current=>current.includes(specialty)?current.filter(item=>item!==specialty):[...current,specialty])
  const answer=async(event)=>{event.preventDefault();try{await api(`/questions/${selected.id}/answers`,{method:'POST',body:JSON.stringify({body:new FormData(event.currentTarget).get('body')})});setPoints(value=>value+20);await load();setFeedback({title:'Answer posted successfully',message:'The operator has been notified and 20 base points were added.'});setSelected(null)}catch(error){setFeedback({title:'Answer could not be posted',message:error.message})}}
  const updateApplication=async(event)=>{event.preventDefault();try{await api('/expert-applications',{method:'POST',body:JSON.stringify({specialty:specialties.join(', '),experience:new FormData(event.currentTarget).get('experience')})});setApplication('Submitted for review');setFeedback({title:'Application submitted',message:'An administrator can now review your experience.'})}catch(error){setFeedback({title:'Application could not be submitted',message:error.message})}}
  return <DashboardLayout user={user} onLogout={onLogout} onSwitchView={onSwitchView} title={tabs.find(x=>x.id===tab).label} subtitle="Share reliable answers and build your reputation." tabs={tabs} activeTab={tab} onTabChange={setTab}>
    {tab==='queue'&&(application==='Approved'?<div className="dashboard-grid"><section className="panel"><div className="board-toolbar"><h4>Open questions</h4><span className="status-badge normal">Verified access</span></div>{questions.filter(q=>!['RESOLVED','CLOSED'].includes(q.status)).map(q=><button className={`question-list-button ${selected?.id===q.id?'active':''}`} key={q.id} onClick={()=>setSelected(q)}><span><strong>{q.title}</strong><small>{q.category} · {new Date(q.createdAt).toLocaleDateString()}</small></span><span className={`status-badge ${q.status==='ESCALATED'?'critical':'normal'}`}>{q.urgency}</span></button>)}</section><section className="panel">{selected?<form className="form-card embedded" onSubmit={answer}><div><span className="pill">{selected.category}</span><h4>{selected.title}</h4><p>{selected.details}</p></div><label>Your verified answer<textarea name="body" required minLength="5" placeholder="Explain the cause and recommended solution" /></label><button className="primary-button">Post answer</button></form>:<div className="empty-state"><strong>Select a question</strong><p>Choose an issue from the queue to review and answer it.</p></div>}</section></div>:<section className="panel verification-gate"><h4>Verification required</h4><p>Only approved experts can answer questions. Submit or review your application status.</p><button className="secondary-button" onClick={()=>setTab('application')}>View application</button></section>)}
    {tab==='answers'&&<section className="panel"><h4>Response history</h4><div className="table-wrap"><table><thead><tr><th>Question</th><th>Status</th><th>Helpful votes</th></tr></thead><tbody>{answers.map(answer=><tr key={answer.id}><td>{answer.question.title}</td><td><span className="status-badge normal">{answer.question.acceptedAnswerId===answer.id?'Accepted':'Answered'}</span></td><td>{answer._count.votes}</td></tr>)}</tbody></table></div></section>}
    {tab==='profile'&&<><section className="public-profile-preview"><div className="public-profile-body"><span className="public-avatar">{user.name[0]}</span><div><h3>{user.name}</h3><p>Verified e-commerce expert · {specialties.join(' · ')}</p></div></div><div className="profile-metrics"><article><strong>{points.toLocaleString()}</strong><span>reputation points</span></article><article><strong>{answers.length}</strong><span>answers posted</span></article><article><strong>{answers.reduce((sum,item)=>sum+item._count.votes,0)}</strong><span>community upvotes</span></article></div></section><section className="panel points-panel compact-points"><h4>How points work</h4><div className="point-list">{pointEvents.map(item=><div className="point-item" key={item.label}><strong>{item.label}</strong><span>{item.value}</span></div>)}</div></section></>}
    {tab==='application'&&<form className="panel dashboard-form expert-application-form" onSubmit={updateApplication}><span className="status-badge normal">{application}</span><h4>Expert verification</h4><fieldset className="specialty-fieldset"><legend>Areas of specialty</legend><div className="specialty-options">{['Checkout','Payments','Theme / Design','Apps'].map(s=><label className={specialties.includes(s)?'selected':''} key={s}><input type="checkbox" checked={specialties.includes(s)} onChange={()=>toggleSpecialty(s)}/><span>{s}</span></label>)}</div></fieldset><label>Professional experience<textarea name="experience" required minLength="10" placeholder="Describe your relevant experience" /></label><button className="primary-button application-submit" disabled={!specialties.length}>Submit application</button></form>}
    <FeedbackModal open={Boolean(feedback)} title={feedback?.title} message={feedback?.message} onClose={()=>setFeedback(null)}/>
  </DashboardLayout>
}
