import { AppHeader } from '../components/AppHeader.jsx'
import { workflowSteps } from '../data/platformData.js'

function ProductMockup({ type }) {
  const content = {
    question: <><span className="mock-label">What do you need help with?</span><b>Checkout button not working</b><i/><span className="mock-label">Category</span><em>Checkout</em><button>Submit question</button></>,
    response: <><span className="mock-status">Verified response</span><b>Maya R. · Checkout specialist</b><p>Check the overlay layer on the mobile breakpoint. It may be blocking the button.</p><span className="mock-accepted">✓ Accepted solution</span></>,
    archive: <><div className="mock-search">⌕ Search solved questions</div><em>Checkout</em><b>Fix for a missing checkout button</b><p>Accepted answer · 48 helpful votes</p><b>Payment email delayed after checkout</b></>,
  }
  return <div className={`product-mockup ${type}`} aria-hidden="true"><div className="browser-bar"><i/><i/><i/></div><div className="mock-content">{content[type]}</div></div>
}

export function LandingPage({ navigate, session }) {
  return <div className="app-shell"><a className="skip-link" href="#main-content">Skip to content</a><AppHeader navigate={navigate}/><main id="main-content">
    <section className="landing-hero panel"><div className="hero-copy"><p className="eyebrow">Support for independent store owners</p><h2>Real e-commerce problems. Verified people. Clear answers.</h2><p className="hero-text">A support community for independent store owners — built around accountable experts and solutions that stay useful.</p><div className="hero-actions"><button className="primary-button" onClick={() => navigate(session ? `/${session.role}` : '/signup')}>{session ? 'Open my dashboard' : 'Get Help'}</button>{!session && <button className="plain-link" onClick={() => navigate('/login')}>Log in</button>}</div></div></section>
    <section id="how-it-works" className="section-block"><div className="section-heading"><p className="eyebrow">How it works</p><h3>A clear path from question to proven solution.</h3></div><div className="workflow-grid">{workflowSteps.slice(0,4).map((step) => <article className="workflow-step" key={step.title}><strong>{step.title}</strong><p>{step.detail.replace('Operator', 'A store owner')}</p></article>)}</div></section>
    <section className="mockup-section section-block"><div className="section-heading"><p className="eyebrow">See the platform in action</p><h3>Simple tools built around getting to an answer.</h3></div><div className="mockup-grid"><article><ProductMockup type="question"/><h4>Ask with the right context</h4><p>A guided form helps you explain the issue clearly from the start.</p></article><article><ProductMockup type="response"/><h4>Hear from verified people</h4><p>Responses show expertise, reputation, and accepted solutions.</p></article><article id="solution-archive"><ProductMockup type="archive"/><h4>Find fixes that already worked</h4><p>Search useful answers by problem, platform, or category.</p></article></div></section>
    <section className="trust-section panel section-block"><div><p className="eyebrow">Built for dependable support</p><h3>Useful signals, after the value is clear.</h3></div><div className="stat-grid"><article className="stat-card"><strong>24h</strong><span>Unanswered-question escalation target</span></article><article className="stat-card"><strong>Verified</strong><span>Experts reviewed before answering</span></article><article className="stat-card"><strong>Searchable</strong><span>Accepted answers preserved in the archive</span></article></div></section>
    <section className="give-help-teaser section-block"><div><p className="eyebrow">Know your way around e-commerce?</p><h3>Turn your experience into answers that help store owners move forward.</h3><p>Build reputation, earn points, and create a public record of useful work.</p></div><button className="secondary-button" onClick={() => navigate('/give-help')}>Explore giving help</button></section>
    <footer className="site-footer simple-footer"><div className="footer-brand"><span className="brand-button"><span className="brand-mark">E</span><span>E-Com Support</span></span><p>Clear, accountable support for independent e-commerce businesses.</p></div><nav aria-label="Footer"><a href="#how-it-works">How It Works</a><a href="#solution-archive">Solution Archive</a><button onClick={() => navigate('/give-help')}>Give Help</button><button onClick={() => navigate('/login')}>Log In</button></nav><span>© {new Date().getFullYear()} E-Com Support Hub</span></footer>
  </main></div>
}
