import { useState } from 'react'
import { DashboardLayout } from '../components/DashboardLayout.jsx'
import { ViewToggle } from '../components/ViewToggle.jsx'
import { FeedbackModal } from '../components/FeedbackModal.jsx'
import { archiveEntries, initialQuestions, sampleThread } from '../data/platformData.js'

const tabs = [{ id: 'overview', label: 'Overview' }, { id: 'ask', label: 'Ask a question' }, { id: 'questions', label: 'My questions' }, { id: 'archive', label: 'Solution archive' }, { id: 'notifications', label: 'Notifications' }, { id: 'profile', label: 'My profile' }]

export function OperatorDashboard({ user, onLogout }) {
  const [tab, setTab] = useState('overview')
  const [questions, setQuestions] = useState(initialQuestions)
  const [view, setView] = useState('table')
  const [accepted, setAccepted] = useState(null)
  const [search, setSearch] = useState('')
  const [category, setCategory] = useState('All')
  const [feedback, setFeedback] = useState(null)
  const [editingQuestion, setEditingQuestion] = useState(null)
  const [profileOpen, setProfileOpen] = useState(false)
  const [profile, setProfile] = useState({ name: user.name, email: user.email, store: 'Ava Home Store', platform: 'Independent storefront', timezone: 'Africa/Lagos', bio: 'Independent store owner focused on creating a simple and reliable shopping experience.' })
  const [preferences, setPreferences] = useState({ answers: true, escalations: true, archive: false, digest: true })
  const [archive, setArchive] = useState(archiveEntries)
  const [votes, setVotes] = useState(Object.fromEntries(archiveEntries.map((item) => [item.id, item.votes])))
  const [voted, setVoted] = useState([])
  const [notifications, setNotifications] = useState([{ id: 1, title: 'New verified answer received', detail: 'Maya R. responded to your checkout question.', time: '8 min ago', unread: true }, { id: 2, title: 'Question escalated', detail: 'Q-2060 was shared with additional payment experts.', time: '1 hr ago', unread: true }, { id: 3, title: 'Solution added to archive', detail: 'Your accepted mobile checkout solution is now searchable.', time: 'Yesterday', unread: false }])
  const submit = (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const id = `Q-${Date.now().toString().slice(-4)}`; setQuestions((items) => [{ id, title: data.get('problem'), category: data.get('category'), status: 'Awaiting expert', age: 'Just now', urgency: 'Normal', responses: 0, escalated: false }, ...items]); setNotifications((items) => [{ id: Date.now(), title: 'Question posted', detail: `${id} is now visible to verified experts.`, time: 'Just now', unread: true }, ...items]); event.currentTarget.reset(); setFeedback({ title: 'Question posted successfully', message: 'Verified experts can now review your request. We will notify you when someone responds.' }); setTab('questions') }
  const acceptSolution = (answer) => { setAccepted(answer.id); setQuestions((items) => items.map((item, index) => index === 0 ? { ...item, status: 'Resolved', escalated: false } : item)); if (!archive.some((item) => item.id === `resolved-${answer.id}`)) { const entry = { id: `resolved-${answer.id}`, title: sampleThread.question, category: 'Checkout', expert: answer.expert, votes: answer.votes, accepted: true, answer: answer.text }; setArchive((items) => [entry, ...items]); setVotes((items) => ({ ...items, [entry.id]: entry.votes })) } setNotifications((items) => [{ id: Date.now(), title: 'Solution accepted', detail: `${answer.expert}'s answer was added to the solution archive.`, time: 'Just now', unread: true }, ...items]); setFeedback({ title: 'Solution accepted', message: `You marked ${answer.expert}'s response as the accepted solution. This question is now preserved in the archive.` }) }
  const upvote = (id) => { if (voted.includes(id)) return; setVotes((items) => ({ ...items, [id]: items[id] + 1 })); setVoted((items) => [...items, id]); setFeedback({ title: 'Answer marked helpful', message: 'Your upvote was recorded and added to the expert’s reputation.' }) }
  const saveQuestionEdit = (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); setQuestions((items) => items.map((item) => item.id === editingQuestion.id && item.responses === 0 ? { ...item, title: data.get('title').trim(), category: data.get('category') } : item)); setEditingQuestion(null); setFeedback({ title: 'Question updated', message: 'Your changes are now visible to experts reviewing the open queue.' }) }
  const saveProfile = (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); setProfile((current) => ({ ...current, name: data.get('name').trim(), store: data.get('store').trim(), platform: data.get('platform'), timezone: data.get('timezone'), bio: data.get('bio').trim() })); setProfileOpen(false); setFeedback({ title: 'Profile updated', message: 'Your personal and store information was saved successfully.' }) }
  const filtered = archive.filter((item) => (item.title + item.answer).toLowerCase().includes(search.toLowerCase()) && (category === 'All' || item.category === category))

  return <DashboardLayout user={user} onLogout={onLogout} title={tab === 'overview' ? `Good day, ${user.name}` : tabs.find((item) => item.id === tab).label} subtitle="Get clear help and track every request." tabs={tabs} activeTab={tab} onTabChange={setTab}>
    {tab === 'overview' && <>
      <section className="operator-welcome"><div><span className="operator-kicker">Your support command center</span><h2>What can we help you solve today?</h2><p>Post a problem in plain language and a verified expert will guide you toward a clear solution.</p><div className="operator-welcome-actions"><button className="primary-button" onClick={() => setTab('ask')}>Ask a new question</button><button className="secondary-button" onClick={() => setTab('archive')}>Search solved issues</button></div></div><div className="sla-card"><span className="sla-icon" aria-hidden="true">24h</span><div><strong>No question ignored</strong><p>Requests without a response are escalated within 24 hours.</p></div></div></section>
      <div className="dashboard-stats operator-stats"><article><span>Open questions</span><strong>{questions.filter((q) => q.status !== 'Resolved').length}</strong><small>Currently being tracked</small></article><article><span>Expert responses</span><strong>{questions.reduce((sum, q) => sum + q.responses, 0)}</strong><small>Across your requests</small></article><article><span>Resolved</span><strong>{questions.filter((q) => q.status === 'Resolved').length + 12}</strong><small>Solutions saved for you</small></article></div>
      <div className="dashboard-grid operator-overview-grid"><section className="panel"><div className="board-toolbar"><div><p className="eyebrow">Request activity</p><h4>Recent questions</h4><p>Latest activity on your support requests.</p></div><button className="text-button" onClick={() => setTab('questions')}>View all →</button></div><div className="operator-request-list">{questions.slice(0, 3).map((q) => <article className="operator-request" key={q.id}><span className={`request-marker ${q.escalated ? 'urgent' : ''}`} aria-hidden="true"/><div><strong>{q.title}</strong><p>{q.category} · {q.age} · {q.responses} responses</p></div><span className={`status-badge ${q.escalated ? 'critical' : 'normal'}`}>{q.status}</span></article>)}</div></section><section className="panel answer-panel"><div className="form-header"><p className="eyebrow">Expert guidance</p><h4>Latest answers</h4><p>Confirm when a response solves your issue.</p></div>{sampleThread.answers.map((answer) => <article className={`thread-answer ${accepted === answer.id ? 'accepted' : ''}`} key={answer.id}><div className="expert-line"><span className="expert-mini-avatar">{answer.expert[0]}</span><strong>{answer.expert}<small>Verified expert</small></strong><span>{answer.votes} helpful</span></div><p>{answer.text}</p><div className="answer-actions"><button className="text-button" onClick={() => acceptSolution(answer)}>{accepted === answer.id ? '✓ Accepted solution' : 'Mark as solution'}</button><button className="helpful-button" onClick={() => setFeedback({ title: 'Thanks for your feedback', message: 'Helpful votes are recorded on each archived solution.' })}>♡ Helpful</button></div></article>)}</section></div>
    </>}
    {tab === 'ask' && <div className="ask-layout"><form className="panel form-card dashboard-form" onSubmit={submit}><div className="form-header"><p className="eyebrow">New support request</p><h4>Tell us what went wrong</h4><p>No technical language or special formatting needed.</p></div><label>What is the problem?<input name="problem" required placeholder="Example: My checkout button is not working" /></label><label>What have you already tried?<textarea name="tried" placeholder="Optional—share any steps you already took" /></label><label>Category<select name="category" required><option>Payments</option><option>Theme / Design</option><option>Apps</option><option>Checkout</option><option>Other</option></select></label><button className="primary-button">Post question</button></form><aside className="panel ask-help"><span className="feature-icon" aria-hidden="true">?</span><h4>A strong question gets a faster answer</h4><ul><li>Describe what you expected to happen.</li><li>Mention the affected device or browser.</li><li>Share any steps you already tried.</li><li>Never include passwords or customer data.</li></ul><div className="help-promise"><strong>24-hour response promise</strong><p>If nobody responds, your question is automatically escalated.</p></div></aside></div>}
    {tab === 'questions' && <section className="panel"><div className="board-toolbar"><div><h4>My support requests</h4><p>You can edit a question until an expert responds.</p></div><ViewToggle value={view} onChange={setView} label="Question view" /></div>{view === 'table' ? <div className="table-wrap" tabIndex="0"><table><thead><tr><th>Question</th><th>Category</th><th>Status</th><th>Age</th><th>Responses</th><th>Action</th></tr></thead><tbody>{questions.map((q) => <tr key={q.id}><td>{q.title}</td><td>{q.category}</td><td><span className={`status-badge ${q.escalated ? 'critical' : 'normal'}`}>{q.status}</span></td><td>{q.age}</td><td>{q.responses}</td><td>{q.responses === 0 ? <button className="text-button" onClick={() => setEditingQuestion(q)}>Edit question</button> : <span className="edit-locked" title="Questions cannot be edited after an expert responds">🔒 Locked</span>}</td></tr>)}</tbody></table></div> : <div className="card-grid">{questions.map((q) => <article className="question-card" key={q.id}><div className="card-topline"><span className="pill">{q.category}</span><span>{q.responses} responses</span></div><h5>{q.title}</h5><div className="question-card-actions"><span className="status-badge normal">{q.status}</span>{q.responses === 0 ? <button className="text-button" onClick={() => setEditingQuestion(q)}>Edit question</button> : <span className="edit-locked">🔒 Editing locked</span>}</div></article>)}</div>}</section>}
    {tab === 'archive' && <section className="panel"><div className="archive-filters"><label>Search solutions<input type="search" value={search} onChange={(e) => setSearch(e.target.value)} /></label><label>Category<select value={category} onChange={(e) => setCategory(e.target.value)}>{['All', 'Payments', 'Theme / Design', 'Apps', 'Checkout'].map((x) => <option key={x}>{x}</option>)}</select></label></div><div className="card-grid">{filtered.map((item) => <article className="archive-card" key={item.id}><div className="card-topline"><span className="pill">{item.category}</span><span className="status-badge normal">Accepted</span></div><h4>{item.title}</h4><p>{item.answer}</p><div className="archive-card-footer"><strong>{item.expert}</strong><button className={`helpful-button ${voted.includes(item.id) ? 'voted' : ''}`} disabled={voted.includes(item.id)} onClick={() => upvote(item.id)}>♥ {votes[item.id]} helpful</button></div></article>)}</div></section>}
    {tab === 'notifications' && <section className="panel notification-center"><div className="board-toolbar"><div><p className="eyebrow">Activity updates</p><h4>Notifications</h4><p>Responses, escalations, and solution activity.</p></div><button className="text-button" onClick={() => setNotifications((items) => items.map((item) => ({ ...item, unread: false })))}>Mark all as read</button></div>{notifications.map((item) => <article className={`notification-row ${item.unread ? 'unread' : ''}`} key={item.id}><span className="notification-dot" aria-hidden="true"/><div><strong>{item.title}</strong><p>{item.detail}</p></div><time>{item.time}</time></article>)}</section>}
    {tab === 'profile' && <div className="operator-profile-layout"><section className="panel operator-profile-card"><div className="operator-profile-cover"><span className="status-badge normal">Active account</span></div><div className="operator-profile-identity"><span className="operator-profile-avatar">{profile.name.charAt(0)}</span><div><h3>{profile.name}</h3><p>Store Operator · Member since June 2026</p></div><button className="secondary-button" onClick={() => setProfileOpen(true)}>Edit profile</button></div><div className="profile-detail-grid"><article><span>Email address</span><strong>{profile.email}</strong></article><article><span>Store name</span><strong>{profile.store}</strong></article><article><span>Commerce platform</span><strong>{profile.platform}</strong></article><article><span>Time zone</span><strong>{profile.timezone}</strong></article></div><div className="profile-bio"><span>About</span><p>{profile.bio}</p></div></section><aside className="profile-side-stack"><section className="panel"><p className="eyebrow">Support activity</p><h4>Your account at a glance</h4><div className="profile-account-stats"><article><strong>{questions.length}</strong><span>questions posted</span></article><article><strong>{questions.filter((item) => item.status === 'Resolved').length + 12}</strong><span>resolved issues</span></article><article><strong>{voted.length}</strong><span>helpful votes</span></article></div></section><section className="panel preference-panel"><p className="eyebrow">Communication</p><h4>Notification preferences</h4>{[{ key: 'answers', label: 'New expert answers', detail: 'When an expert responds to your question' }, { key: 'escalations', label: 'Escalation updates', detail: 'When a request passes the response threshold' }, { key: 'archive', label: 'Archive recommendations', detail: 'Related solutions matching your questions' }, { key: 'digest', label: 'Weekly support digest', detail: 'A summary of your support activity' }].map((item) => <label className="preference-toggle" key={item.key}><span><strong>{item.label}</strong><small>{item.detail}</small></span><input type="checkbox" checked={preferences[item.key]} onChange={() => setPreferences((current) => ({ ...current, [item.key]: !current[item.key] }))}/><i aria-hidden="true"/></label>)}</section></aside></div>}
    {editingQuestion && <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setEditingQuestion(null) }}><section className="confirmation-modal question-edit-modal" role="dialog" aria-modal="true" aria-labelledby="edit-question-title"><p className="eyebrow">Open question · {editingQuestion.id}</p><h2 id="edit-question-title">Edit your question</h2><p>You can update this request because no expert has responded yet.</p><form onSubmit={saveQuestionEdit}><label>What is the problem?<input name="title" defaultValue={editingQuestion.title} required /></label><label>Category<select name="category" defaultValue={editingQuestion.category}><option>Payments</option><option>Theme / Design</option><option>Apps</option><option>Checkout</option><option>Other</option></select></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setEditingQuestion(null)}>Cancel</button><button type="submit" className="primary-button">Save changes</button></div></form></section></div>}
    {profileOpen && <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setProfileOpen(false) }}><section className="confirmation-modal profile-edit-modal" role="dialog" aria-modal="true" aria-labelledby="edit-profile-title"><p className="eyebrow">Account settings</p><h2 id="edit-profile-title">Edit your profile</h2><p>Keep your personal and store information current.</p><form onSubmit={saveProfile}><div className="profile-form-grid"><label>Full name<input name="name" defaultValue={profile.name} required /></label><label>Store name<input name="store" defaultValue={profile.store} required /></label><label>Commerce platform<select name="platform" defaultValue={profile.platform}><option>Independent storefront</option><option>Shopify</option><option>WooCommerce</option><option>BigCommerce</option><option>Other</option></select></label><label>Time zone<select name="timezone" defaultValue={profile.timezone}><option>Africa/Lagos</option><option>Europe/London</option><option>America/New_York</option><option>America/Los_Angeles</option><option>Asia/Dubai</option></select></label><label className="profile-form-wide">About you<textarea name="bio" defaultValue={profile.bio} maxLength="240" rows="4" /></label></div><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setProfileOpen(false)}>Cancel</button><button type="submit" className="primary-button">Save profile</button></div></form></section></div>}
    <FeedbackModal open={Boolean(feedback)} title={feedback?.title} message={feedback?.message} onClose={() => setFeedback(null)} />
  </DashboardLayout>
}
