import { useEffect, useMemo, useRef, useState } from 'react'
import { DashboardLayout } from '../components/DashboardLayout.jsx'
import { ViewToggle } from '../components/ViewToggle.jsx'
import { FeedbackModal } from '../components/FeedbackModal.jsx'
import { InlineActivity } from '../components/InlineActivity.jsx'
import { api, nextPaint } from '../lib/api.js'

const tabs=[{id:'overview',label:'Overview'},{id:'ask',label:'Ask a question'},{id:'questions',label:'My questions'},{id:'archive',label:'Solution archive'},{id:'notifications',label:'Notifications'},{id:'profile',label:'My profile'}]
const formatQuestion=q=>({...q,status:q.status.replaceAll('_',' ').toLowerCase().replace(/^./,x=>x.toUpperCase()),age:new Date(q.createdAt).toLocaleDateString(),urgency:q.urgency==='MEDIUM'?'Normal':q.urgency,responses:q._count?.answers??q.answers?.length??0,escalated:q.status==='ESCALATED'})

export function OperatorDashboard({user,onLogout,onSwitchView}){
  const loadSequence=useRef(0)
  const [initialLoading,setInitialLoading]=useState(true)
  const [tab,setTab]=useState('overview');const [questions,setQuestions]=useState([]);const [archive,setArchive]=useState([]);const [notifications,setNotifications]=useState([]);const [categories,setCategories]=useState([])
  const [profile,setProfile]=useState({name:user.name,email:user.email,store:'',platform:'',timezone:'Africa/Lagos',bio:''});const [preferences,setPreferences]=useState({answers:true,escalations:true,archive:false,digest:true})
  const [view,setView]=useState('table');const [search,setSearch]=useState('');const [category,setCategory]=useState('All');const [feedback,setFeedback]=useState(null);const [editingQuestion,setEditingQuestion]=useState(null);const [profileOpen,setProfileOpen]=useState(false);const [voted,setVoted]=useState([])
  const load=()=>{const sequence=++loadSequence.current;return Promise.all([api('/questions?scope=mine'),api('/archive'),api('/notifications'),api('/profile'),api('/categories')]).then(([questionItems,archiveItems,noticeItems,profileItem,categoryItems])=>{if(sequence!==loadSequence.current)return;setQuestions(questionItems.map(formatQuestion));setArchive(archiveItems.map(q=>({id:q.id,answerId:q.acceptedAnswerId,title:q.title,category:q.category,expert:q.acceptedAnswer.author.name,votes:q.acceptedAnswer._count.votes,answer:q.acceptedAnswer.body})));setNotifications(noticeItems);setProfile({name:profileItem.name,email:profileItem.email,store:profileItem.store||'',platform:profileItem.platform||'',timezone:profileItem.timezone||'Africa/Lagos',bio:profileItem.bio||''});setPreferences(profileItem.preferences);setCategories(categoryItems.filter(x=>x.isActive).map(x=>x.name))})}
  useEffect(()=>{load().catch(error=>setFeedback({title:'Dashboard could not be loaded',message:error.message})).finally(()=>setInitialLoading(false))},[])
  const latestAnswers=useMemo(()=>questions.flatMap(question=>(question.answers||[]).map(answer=>({question,answer}))).sort((a,b)=>new Date(b.answer.createdAt)-new Date(a.answer.createdAt)).slice(0,3),[questions])
  const filtered=archive.filter(item=>(item.title+item.answer+item.expert).toLowerCase().includes(search.toLowerCase())&&(category==='All'||item.category===category))
  const submit=async event=>{event.preventDefault();const form=event.currentTarget;const data=new FormData(form);try{const created=await api('/questions',{method:'POST',body:JSON.stringify({title:data.get('problem'),details:data.get('details'),tried:data.get('tried')||undefined,category:data.get('category'),urgency:'MEDIUM'})});loadSequence.current+=1;setQuestions(items=>[formatQuestion({...created,answers:[],_count:{answers:0}}),...items]);form.reset();setTab('questions');await nextPaint();setFeedback({title:'Question posted successfully',message:'Verified experts can now review your request.'});load().catch(()=>{})}catch(error){setFeedback({title:'Question could not be posted',message:error.message})}}
  const acceptSolution=async(question,answer)=>{try{await api(`/questions/${question.id}/answers/${answer.id}/accept`,{method:'POST'});await load();await nextPaint();setFeedback({title:'Solution accepted',message:`You marked ${answer.author.name}'s response as the accepted solution.`})}catch(error){setFeedback({title:'Solution could not be accepted',message:error.message})}}
  const upvote=async answerId=>{if(voted.includes(answerId))return;try{await api(`/questions/answers/${answerId}/vote`,{method:'POST'});setVoted(items=>[...items,answerId]);await load();await nextPaint();setFeedback({title:'Answer marked helpful',message:'Your vote was recorded and the expert earned reputation.'})}catch(error){setFeedback({title:'Vote could not be recorded',message:error.message})}}
  const saveQuestionEdit=async event=>{event.preventDefault();const data=new FormData(event.currentTarget);try{const updated=await api(`/questions/${editingQuestion.id}`,{method:'PATCH',body:JSON.stringify({title:data.get('title').trim(),category:data.get('category')})});loadSequence.current+=1;setQuestions(items=>items.map(item=>item.id===updated.id?{...item,...updated,status:item.status,age:item.age,responses:item.responses}:item));setEditingQuestion(null);await nextPaint();setFeedback({title:'Question updated',message:'Your changes are now visible to experts.'});load().catch(()=>{})}catch(error){setFeedback({title:'Question could not be updated',message:error.message})}}
  const saveProfile=async event=>{event.preventDefault();const data=new FormData(event.currentTarget);try{await api('/profile',{method:'PATCH',body:JSON.stringify({name:data.get('name').trim(),store:data.get('store').trim(),platform:data.get('platform'),timezone:data.get('timezone'),bio:data.get('bio').trim(),preferences})});await load();setProfileOpen(false);await nextPaint();setFeedback({title:'Profile updated',message:'Your account information was saved.'})}catch(error){setFeedback({title:'Profile could not be updated',message:error.message})}}
  const togglePreference=async key=>{const previous=preferences;const next={...previous,[key]:!previous[key]};setPreferences(next);try{await api('/profile',{method:'PATCH',body:JSON.stringify({preferences:next})})}catch(error){setPreferences(previous);setFeedback({title:'Preference could not be saved',message:error.message})}}
  const markAllRead=async()=>{try{await api('/notifications/read-all',{method:'PATCH'});setNotifications(items=>items.map(item=>({...item,isRead:true})))}catch(error){setFeedback({title:'Notifications could not be updated',message:error.message})}}
  return <DashboardLayout user={user} onLogout={onLogout} onSwitchView={onSwitchView} title={tab==='overview'?`Good day, ${profile.name}`:tabs.find(x=>x.id===tab).label} subtitle="Get clear help and track every request." tabs={tabs} activeTab={tab} onTabChange={setTab}>
    {tab==='overview'&&<>
      <section className="operator-welcome"><div><span className="operator-kicker">Your support command center</span><h2>What can we help you solve today?</h2><p>Post a problem in plain language and a verified expert will guide you toward a clear solution.</p><div className="operator-welcome-actions"><button className="primary-button" onClick={()=>setTab('ask')}>Ask a new question</button><button className="secondary-button" onClick={()=>setTab('archive')}>Search solved issues</button></div></div></section>
      <div className="dashboard-stats operator-stats"><article><span>Open questions</span><strong>{initialLoading?<InlineActivity label="Loading open questions"/>:questions.filter(q=>q.status!=='Resolved').length}</strong></article><article><span>Expert responses</span><strong>{initialLoading?<InlineActivity label="Loading expert responses"/>:questions.reduce((sum,q)=>sum+q.responses,0)}</strong></article><article><span>Resolved</span><strong>{initialLoading?<InlineActivity label="Loading resolved questions"/>:questions.filter(q=>q.status==='Resolved').length}</strong></article></div>
      <div className="dashboard-grid operator-overview-grid"><section className="panel"><h4>Recent questions</h4>{initialLoading?<div className="inline-panel-loading"><InlineActivity label="Loading recent questions"/></div>:questions.length?questions.slice(0,3).map(q=><article className="operator-request" key={q.id}><div><strong>{q.title}</strong><p>{q.category} · {q.age} · {q.responses} {q.responses===1?'response':'responses'}</p></div><span className={`status-badge ${q.escalated?'critical':'normal'}`}>{q.status}</span></article>):<div className="empty-state compact-empty"><strong>No questions yet</strong></div>}</section><section className="panel answer-panel"><h4>Latest answers</h4>{initialLoading?<div className="inline-panel-loading"><InlineActivity label="Loading latest answers"/></div>:latestAnswers.length?latestAnswers.map(({question,answer})=><article className="thread-answer" key={answer.id}><div className="expert-line"><strong>{answer.author.name}<small>Verified expert</small></strong><span>{answer._count.votes} helpful</span></div><p>{answer.body}</p><div className="answer-actions"><button className="text-button" onClick={()=>acceptSolution(question,answer)}>{question.acceptedAnswerId===answer.id?'✓ Accepted solution':'Mark as solution'}</button><button className="helpful-button" onClick={()=>upvote(answer.id)}>♡ Helpful</button></div></article>):<div className="empty-state"><strong>No answers yet</strong><p>Expert replies will appear here.</p></div>}</section></div>
    </>}
    {tab==='ask'&&<section className="panel dashboard-form operator-question-form"><form onSubmit={submit}><label>What is the problem?<input name="problem" required minLength="5"/></label><label>Describe the issue<textarea name="details" required minLength="10"/></label><label>What have you tried?<textarea name="tried"/></label><label>Category<select className="category-select" name="category" required>{categories.map(x=><option key={x}>{x}</option>)}</select></label><button className="primary-button">Submit question</button></form></section>}
    {tab==='questions'&&<section className="panel"><div className="board-toolbar"><h4>My questions</h4><ViewToggle value={view} onChange={setView} label="Question display"/></div>{view==='table'?<div className="table-wrap"><table><thead><tr><th>Question</th><th>Category</th><th>Status</th><th>Responses</th><th>Action</th></tr></thead><tbody>{questions.map(q=><tr key={q.id}><td><strong>{q.title}</strong></td><td>{q.category}</td><td>{q.status}</td><td>{q.responses}</td><td>{q.responses===0&&<button className="text-button" onClick={()=>setEditingQuestion(q)}>Edit</button>}</td></tr>)}</tbody></table></div>:<div className="question-card-grid">{questions.map(q=><article className="question-card operator-question-card" key={q.id}><div className="card-topline"><span className="pill">{q.category}</span><span className={`status-badge ${q.escalated?'critical':'normal'}`}>{q.status}</span></div><h4>{q.title}</h4><p>{q.age} · {q.responses} {q.responses===1?'response':'responses'}</p><div className="question-card-actions">{q.responses===0?<button className="text-button" onClick={()=>setEditingQuestion(q)}>Edit question</button>:<span>Expert activity received</span>}</div></article>)}</div>}</section>}
    {tab==='archive'&&<section className="panel"><div className="archive-controls"><label>Search<input value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{['All',...categories].map(x=><option key={x}>{x}</option>)}</select></label></div><div className="card-grid">{filtered.map(item=><article className="archive-card" key={item.id}><span className="pill">{item.category}</span><h4>{item.title}</h4><p>{item.answer}</p><div className="archive-card-footer"><strong>{item.expert}</strong><button className="helpful-button" disabled={voted.includes(item.answerId)} onClick={()=>upvote(item.answerId)}>♡ {item.votes} helpful</button></div></article>)}</div></section>}
    {tab==='notifications'&&<section className="panel notification-center"><div className="board-toolbar"><h4>Notifications</h4><button className="text-button" onClick={markAllRead}>Mark all as read</button></div>{notifications.map(item=><article className={`notification-row ${!item.isRead?'unread':''}`} key={item.id}><span className="notification-dot"/><div><strong>{item.title}</strong><p>{item.detail}</p></div><time>{new Date(item.createdAt).toLocaleString()}</time></article>)}</section>}
    {tab==='profile'&&<div className="operator-profile-layout"><section className="panel operator-profile-card"><div className="operator-profile-identity"><span className="operator-profile-avatar">{profile.name[0]}</span><div><h3>{profile.name}</h3><p>{profile.email}</p></div><button className="secondary-button" onClick={()=>setProfileOpen(true)}>Edit profile</button></div><div className="profile-detail-grid"><article><span>Store name</span><strong>{profile.store||'Not provided'}</strong></article><article><span>Commerce platform</span><strong>{profile.platform||'Not provided'}</strong></article><article><span>Time zone</span><strong>{profile.timezone}</strong></article></div><div className="profile-bio"><span>About</span><p>{profile.bio||'No bio provided.'}</p></div></section><aside className="panel preference-panel"><h4>Notification preferences</h4>{Object.entries({answers:'New expert answers',escalations:'Escalation updates',archive:'Archive recommendations',digest:'Weekly support digest'}).map(([key,label])=><label className="preference-toggle" key={key}><span><strong>{label}</strong></span><input type="checkbox" checked={preferences[key]} onChange={()=>togglePreference(key)}/><i/></label>)}</aside></div>}
    {editingQuestion&&<div className="modal-backdrop"><section className="confirmation-modal"><h2>Edit your question</h2><form onSubmit={saveQuestionEdit}><label>Question<input name="title" defaultValue={editingQuestion.title} required/></label><label>Category<select name="category" defaultValue={editingQuestion.category}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><div className="modal-actions"><button type="button" onClick={()=>setEditingQuestion(null)}>Cancel</button><button className="primary-button">Save</button></div></form></section></div>}
    {profileOpen&&<div className="modal-backdrop"><section className="confirmation-modal profile-edit-modal"><h2>Edit your profile</h2><form onSubmit={saveProfile}><label>Full name<input name="name" defaultValue={profile.name} required/></label><label>Store name<input name="store" defaultValue={profile.store}/></label><label>Commerce platform<input name="platform" defaultValue={profile.platform}/></label><label>Time zone<input name="timezone" defaultValue={profile.timezone}/></label><label>About<textarea name="bio" defaultValue={profile.bio}/></label><div className="modal-actions"><button type="button" onClick={()=>setProfileOpen(false)}>Cancel</button><button className="primary-button">Save profile</button></div></form></section></div>}
    <FeedbackModal open={Boolean(feedback)} title={feedback?.title} message={feedback?.message} onClose={()=>setFeedback(null)}/>
  </DashboardLayout>
}
