import { useState } from 'react'
import { DashboardLayout } from '../components/DashboardLayout.jsx'
import { ViewToggle } from '../components/ViewToggle.jsx'
import { archiveEntries, initialQuestions, sampleThread } from '../data/platformData.js'

const tabs = [{ id: 'overview', label: 'Overview' }, { id: 'ask', label: 'Ask a question' }, { id: 'questions', label: 'My questions' }, { id: 'archive', label: 'Solution archive' }]

export function OperatorDashboard({ user, onLogout }) {
  const [tab, setTab] = useState('overview')
  const [questions, setQuestions] = useState(initialQuestions)
  const [view, setView] = useState('table')
  const [accepted, setAccepted] = useState(null)
  const [search, setSearch] = useState('')
  const [category, setCategory] = useState('All')
  const [notice, setNotice] = useState('')
  const submit = (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); setQuestions((items) => [{ id: `Q-${Date.now().toString().slice(-4)}`, title: data.get('problem'), category: data.get('category'), status: 'Awaiting expert', age: 'Just now', urgency: 'Normal', responses: 0, escalated: false }, ...items]); event.currentTarget.reset(); setNotice('Your question was posted. We will notify you when an expert responds.'); setTab('questions') }
  const filtered = archiveEntries.filter((item) => (item.title + item.answer).toLowerCase().includes(search.toLowerCase()) && (category === 'All' || item.category === category))

  return <DashboardLayout user={user} onLogout={onLogout} title={tab === 'overview' ? `Good day, ${user.name}` : tabs.find((item) => item.id === tab).label} subtitle="Get clear help and track every request." tabs={tabs} activeTab={tab} onTabChange={setTab}>
    {tab === 'overview' && <>
      <section className="operator-welcome"><div><span className="operator-kicker">Your support command center</span><h2>What can we help you solve today?</h2><p>Post a problem in plain language and a verified expert will guide you toward a clear solution.</p><div className="operator-welcome-actions"><button className="primary-button" onClick={() => setTab('ask')}>Ask a new question</button><button className="secondary-button" onClick={() => setTab('archive')}>Search solved issues</button></div></div><div className="sla-card"><span className="sla-icon" aria-hidden="true">24h</span><div><strong>No question ignored</strong><p>Requests without a response are escalated within 24 hours.</p></div></div></section>
      <div className="dashboard-stats operator-stats"><article><span>Open questions</span><strong>{questions.filter((q) => q.status !== 'Resolved').length}</strong><small>Currently being tracked</small></article><article><span>Expert responses</span><strong>{questions.reduce((sum, q) => sum + q.responses, 0)}</strong><small>Across your requests</small></article><article><span>Resolved</span><strong>{questions.filter((q) => q.status === 'Resolved').length + 12}</strong><small>Solutions saved for you</small></article></div>
      <div className="dashboard-grid operator-overview-grid"><section className="panel"><div className="board-toolbar"><div><p className="eyebrow">Request activity</p><h4>Recent questions</h4><p>Latest activity on your support requests.</p></div><button className="text-button" onClick={() => setTab('questions')}>View all →</button></div><div className="operator-request-list">{questions.slice(0, 3).map((q) => <article className="operator-request" key={q.id}><span className={`request-marker ${q.escalated ? 'urgent' : ''}`} aria-hidden="true"/><div><strong>{q.title}</strong><p>{q.category} · {q.age} · {q.responses} responses</p></div><span className={`status-badge ${q.escalated ? 'critical' : 'normal'}`}>{q.status}</span></article>)}</div></section><section className="panel answer-panel"><div className="form-header"><p className="eyebrow">Expert guidance</p><h4>Latest answers</h4><p>Confirm when a response solves your issue.</p></div>{sampleThread.answers.map((answer) => <article className={`thread-answer ${accepted === answer.id ? 'accepted' : ''}`} key={answer.id}><div className="expert-line"><span className="expert-mini-avatar">{answer.expert[0]}</span><strong>{answer.expert}<small>Verified expert</small></strong><span>{answer.votes} helpful</span></div><p>{answer.text}</p><button className="text-button" onClick={() => setAccepted(answer.id)}>{accepted === answer.id ? '✓ Accepted solution' : 'Mark as solution'}</button></article>)}</section></div>
    </>}
    {tab === 'ask' && <div className="ask-layout"><form className="panel form-card dashboard-form" onSubmit={submit}><div className="form-header"><p className="eyebrow">New support request</p><h4>Tell us what went wrong</h4><p>No technical language or special formatting needed.</p></div><label>What is the problem?<input name="problem" required placeholder="Example: My checkout button is not working" /></label><label>What have you already tried?<textarea name="tried" placeholder="Optional—share any steps you already took" /></label><label>Category<select name="category" required><option>Payments</option><option>Theme / Design</option><option>Apps</option><option>Checkout</option><option>Other</option></select></label><button className="primary-button">Post question</button></form><aside className="panel ask-help"><span className="feature-icon" aria-hidden="true">?</span><h4>A strong question gets a faster answer</h4><ul><li>Describe what you expected to happen.</li><li>Mention the affected device or browser.</li><li>Share any steps you already tried.</li><li>Never include passwords or customer data.</li></ul><div className="help-promise"><strong>24-hour response promise</strong><p>If nobody responds, your question is automatically escalated.</p></div></aside></div>}
    {tab === 'questions' && <section className="panel"><div className="board-toolbar"><div><h4>My support requests</h4><p>Questions are automatically escalated if unanswered.</p></div><ViewToggle value={view} onChange={setView} label="Question view" /></div>{notice && <p className="success-notice" role="status">{notice}</p>}{view === 'table' ? <div className="table-wrap" tabIndex="0"><table><thead><tr><th>Question</th><th>Category</th><th>Status</th><th>Age</th><th>Responses</th></tr></thead><tbody>{questions.map((q) => <tr key={q.id}><td>{q.title}</td><td>{q.category}</td><td><span className={`status-badge ${q.escalated ? 'critical' : 'normal'}`}>{q.status}</span></td><td>{q.age}</td><td>{q.responses}</td></tr>)}</tbody></table></div> : <div className="card-grid">{questions.map((q) => <article className="question-card" key={q.id}><span className="pill">{q.category}</span><h5>{q.title}</h5><span className="status-badge normal">{q.status}</span></article>)}</div>}</section>}
    {tab === 'archive' && <section className="panel"><div className="archive-filters"><label>Search solutions<input type="search" value={search} onChange={(e) => setSearch(e.target.value)} /></label><label>Category<select value={category} onChange={(e) => setCategory(e.target.value)}>{['All', 'Payments', 'Theme / Design', 'Apps', 'Checkout'].map((x) => <option key={x}>{x}</option>)}</select></label></div><div className="card-grid">{filtered.map((item) => <article className="archive-card" key={item.id}><span className="pill">{item.category}</span><h4>{item.title}</h4><p>{item.answer}</p><strong>{item.expert} · {item.votes} helpful votes</strong></article>)}</div></section>}
  </DashboardLayout>
}
